### ISSUE TITLE
[Feature Request] Add support to different layouts on different monitors

### ISSUE THREAD

**Issue by domferr** [domferr/tilingshell#1]
Currently, the selected layout is applied to all the monitors. The idea is to allow a different layout for each monitor.
The current codebase is ready to accommodate the needed changes, so it should be enough only to add a new layout selection setting and some easy changes to remember each monitor's layout to apply on startup if the computer was suspended.

However, we still want to allow the current behaviour, meaning that it must be possible to quickly change the monitor layouts with just one click.

If you want to contribute but don't know how to start, I'll be more than glad to guide you.

This is a mockup, feel free to share any ideas!

![monitor_layouts_mockup](https://github.com/domferr/modernwindowmanager/assets/14203981/f1460f17-cbaa-4c72-90eb-a9330297739a)

**Comment by in4matix** [comment]
Hey! I did warn you about the wining bunch on GSE... The mock-up looks good to me, but I use one large desktop monitor, so yeah, not an issue for me. But if did I use multiple monitors, this makes perfect sense. I see the other ungrateful critic wants hot-keys... Who wants to remember a bunch of extra hot-keys?! , when you can just grab the window by it's ears and put it just about anywhere, and still resize it there... But, yeah, you can please some of the people some of the time, but not all of the people all of the time... All the best.

**Comment by in4matix** [comment]
The person is comparing it to Tiling Assistant https://github.com/Leleat/Tiling-Assistant . I have used it in the passed, and Ubuntu 24 has it as a system extension, but look at the list of hot-keys, plus, of late, it's been having a lot of issues and getting negative reviews.

**Comment by in4matix** [comment]
It is one of those Applications where the Dev just kept on adding extras, and now it has become too complicated to maintain. They forgot about the good old KIS principle.

**Comment by in4matix** [comment]
BTW. I see that you have also separated notifications from your calendar. May I ask witch extension you are using for that?

**Comment by domferr** [comment]
> BTW. I see that you have also separated notifications from your calendar. May I ask witch extension you are using for that?

Uh, I really don't remember. It was something I was trying last February, but don't remember the name :\

**Comment by cadamantidis** [comment]
is this being actively worked on?

**Comment by domferr** [comment]
Hi @cadamantidis, currently I'm not working on this. Since there are many requests, if many people suggest this feature I will prioritize it over the others!

Moreover, if anyone wants to contribute to an open source project for the first time or learn gnome extension development, this could be a nice start! I'm open to give any help

**Comment by czQery** [comment]
I am interested too, I think this is an essential feature

**Comment by domferr** [comment]
What do you guys think about the mockup above? How would you like to select a different layout for each monitor?

**Comment by EfogDev** [comment]
@domferr btw it would be great if using the snap assistant will update the active layout

**Comment by mattdm** [comment]
Love this. I have a three-monitor setup, like this:

* Left: landscape mode 16:10
* Middle: a teleprompter setup with a 14" monitor used for video calls -- 16:9[^1]
* Right: portrait mode

On the left, I want something set up to easily toggle between a web browsing mode (centered big space, small spaces on the side), a 2-column view, and a coding mode which has some smaller specific divisions. The center, I'd want to always be one big full-screen (ideal if it automatically makes the window full-screen, hiding window decorations). And on the right, I want full-screen or vertically split into two or three.

[^1]: I'd love a 4:3 monitor here, TBH, because that'd fit the teleprompter setup better. But those are all stupidly expensive.

**Comment by mattdm** [comment]
> What do you guys think about the mockup above? How would you like to select a different layout for each monitor?

Is it possible to add choices to the highly-underutilized right-click-on-wallpaper menu? It's basically things I do extremely rarely[^1] and seems both logical and quick for changing layouts.

Another idea would be to add layout choices to the overview -- maybe something on the dash, but ideally _on each monitor_, so maybe a new control panel, configurable to be in any corner?

[^1]: change wallpaper, go to display settings, and go to settings -- the last bringing you to whatever settings panel you were last using, which is less useful than searching for the specific thing in the overview

**Comment by domferr** [comment]
Thank you @mattdm for your suggestions! They are much appreciated :100: 

Since I use a 21:9 monitor and a 16:9 secondary monitor, when I designed Tiling Shell I decided to support per-monitor layouts :laughing:: the good news is that the source code already supports it, but I didn't expose it in the preferences or somewhere else.
I'm going to start to work on this next week, stay tuned!

> Is it possible to add choices to the highly-underutilized right-click-on-wallpaper menu?

:open_mouth: I didn't think about it! It's not that bad, however I'm not sure it can be done. I'll do some research on this :+1:

**Comment by domferr** [comment]
A little update for you. This feature is ready to be tested! :partying_face:. It has the following look and feel if you have multiple monitors.

<p align="center">
<img src="https://github.com/domferr/tilingshell/assets/14203981/b26b65d5-2f77-4b67-b659-a81abafaf3bf" />
</p>

If the monitor is just one, everything looks like before (there isn't the "_monitor 1_" text).

I leave here the files [^1] if you want to try it in advance! If you do, please give me your feedback, thank you!
- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16050678/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16050684/tilingshell%40ferrarodomenico.com.zip)

My thoughts:
- I don't like the text "_monitor 1_", "_monitor 2_" and so on...Which one is "_monitor 1_"? This doesn't tell anything about which of the physical monitors is the number 1! I'd like to use the monitor name, however, to be honest, I don't know how to do it and I didn't find similar things in any extension or gnome-shell repository. The only solution is to ask gnome-shell developers...
- The indicator was polished, but now it is a bit messy. There are too many things there now
- This solution doesn't allow to select a layout for each monitor with just one click

However, it may not be perfect, but I believe it is more beneficial for everybody if I publish this feature instead of spending too much time on it.

[^1]: If you don't know how to install, here it is a little guide for you. You need to perform the following steps: overwrite the files into `.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com` with the ones in the archive I shared, then log out and log in (or restart the system).

**Comment by domferr** [comment]
Well...it turns out it is **not** possible to get the monitors' name. I implemented a **workaround**, which works quite well on my system:
<p align="center">
<img src="https://github.com/domferr/tilingshell/assets/14203981/d0261742-eb7c-4fbf-ab7b-da638d31378c" />
</p>

If there are errors on getting the monitors' name, the labels "Monitor 1", "Monitor 2" and so on, are used instead (left :arrow_left: image). If the monitor is just one, everything looks like before (there isn't the "_monitor name_" text) (right :arrow_right: image).

<p align="center">
<img src="https://github.com/domferr/tilingshell/assets/14203981/53b5b345-39c4-4051-8475-0902e60b5d79" width=300 />
<img src="https://github.com/domferr/tilingshell/assets/14203981/be4bb15d-35cb-4a26-b842-131496be3ce4"  width=360/>
</p>

I leave here the files [^1] if you want to try it in advance! If you do, please give me your feedback, thank you!
- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16090873/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16090874/tilingshell%40ferrarodomenico.com.zip)

[^1]: If you don't know how to install, here it is a little guide for you. You need to perform the following steps: overwrite the files into `.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com` with the ones in the archive I shared, then log out and log in (or restart the system).
