### ISSUE TITLE
Repeated updates

### ISSUE THREAD

**Issue by in4matix** [domferr/tilingshell#101]
Extension updated yesterday and now again this morning..?
Oh, and while I am here ;-) the window menu is off-center (everything is to the right) ... Sorry for nitpicking but I am a painful perfectionist and this is driving me nuts. Lol 

![Screenshot from 2024-07-23 08-45-23](https://github.com/user-attachments/assets/d148f6c5-538f-4d02-a574-428c4939dba3)

Ubuntu 22.04

**Comment by domferr** [comment]
Hey, yeah the update was solving an important regression (issue #99).

Speaking about the window menu...ehm I don't know why but the GNOME design team decided to implement it in that way ahahah. Tiling Shell just extends it, following the same design, otherwise it seems off

**Comment by in4matix** [comment]
Hey,
Thanks for explaining. I am starting to dislike Gnome somewhat. Looking forward to Cosmic DE.
