### ISSUE TITLE
[Feature Request] Ability to change layouts order

### ISSUE THREAD

**Issue by VolodymyrPanasyuk** [domferr/tilingshell#106]
**Description**
Please add functionality in "Edit Layouts" mode to change the order of layouts using Drag and Drop or using buttons.

**Example**
![Screenshot from 2024-07-24 18-09-38](https://github.com/user-attachments/assets/e671f969-d3da-49b6-b76a-ce36396c10a2)

**Comment by domferr** [comment]
Hi, thank you for sharing your idea. This is already discussed in #90, see you there!

Btw, I like your screenshot, the drag and drop idea and the possibility to move using buttons.

**Comment by domferr** [comment]
Let's continue the discussion in https://github.com/domferr/tilingshell/issues/90
