### ISSUE TITLE
Appindicator is undefined

### ISSUE THREAD

**Issue by horga83** [domferr/tilingshell#107]
**Describe the bug**
Extension doesn't run, throws "TypeError: appIndicator is undefined"

**To Reproduce**
Install extension

**Screenshots**

**Information (please complete the following):**
 - Tiling Shell version: [e.g. v9.0]
Extension app shows version 22

 - GNOME version: [e.g. 42, 46]. If you don't know, run `gnome-shell --version`
Gnome shell 46 under Arch

**Additional context**

**Comment by domferr** [comment]
Hey, thank you for sharing this issue! It sounds strange: there is nothing named `appIndicator` in the whole extension.

Can you run `journalctl -b /usr/bin/gnome-shell -n 300 --no-pager` and look to any error related to Tiling Shell? Thank you!

**Comment by horga83** [comment]
Hey sorry for not getting back right away, was away.  I ran the command and did not find any issue with Tiling Shell.
Will investigate further.

Many thanks
