### ISSUE TITLE
 [Feature Request] Add a hotkey to use all tiles in layout.

### ISSUE THREAD

**Issue by joaocandre** [domferr/tilingshell#114]
It would be nice to replace Gnome's default 'maximize' behavior (Alt + Up) with a 'Merge All Tiles' feature, as is currently being triggered by dragging to the top of the screen. In practice it would pseudo-maximize the window, but in a way more consistent with the tiling behavior (e.g. borders)

Alternatively, since Alt + Up is already being used to select the top tile, perhaps a different (custom?) keybinding could be used.

**Comment by domferr** [comment]
Hey, thank you for your suggestion! This sounds nice :smile:

**Comment by domferr** [comment]
Hey, I'm looking into implement this! Do you have any idea about how to call it?

**Comment by joaocandre** [comment]
@domferr going with the extension feature nomenclature, I guess 'Span All Tiles'?

**Comment by domferr** [comment]
:star: Now available in [Tiling Shell v13](https://github.com/domferr/tilingshell/releases/tag/13.0.0)!
