### ISSUE TITLE
[Feature Request] Navigate between windows with keyboard shortcuts

### ISSUE THREAD

**Issue by distefam** [domferr/tilingshell#116]
**Describe the feature you'd like**
I would like to be able to navigate between windows with hotkeys. Currently, I supplement tiling-shell with an additional extension called [Focus changer](https://extensions.gnome.org/extension/4627/focus-changer/) to get this functionality but I think it makes sense to include it in this extension since it is directly related to tiling.

**Additional context**
I have the following keybindings configured:
- **Tiling Shell:** (move windows) `<Shift><Super>h,j,k,l`
- **Focus Changer:** (select window) `<Super>h,j,k,l`

**Comment by domferr** [comment]
Hey @distefam thank you for sharing this idea! I think this would be a nice addition to Tiling Shell

**Comment by thyttan** [comment]
Similar to #69.

Thanks for the Focus changer extension tip!

**Comment by domferr** [comment]
Hey, quick update for you! This feature is now ready and it is going to be released with the next upcoming version! :soon:

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!
