### ISSUE TITLE
[Feature Request] Workspace-specific layouts

### ISSUE THREAD

**Issue by distefam** [domferr/tilingshell#118]
**Describe the feature you'd like**
Tie a specific layout to a particular workspace. In other words, be able to either:
- specify that a layout should be the default for a given workspace
- remember the last-used layout per workspace

Personally, I think I'd prefer the second option, which would work better with dynamic workspaces.

**Comment by thyttan** [comment]
Similarity with #47.

**Comment by domferr** [comment]
Hey, thank you for sharing this idea. Check #47 out! We did some brainstorming there. Hope to implement this feature soon :partying_face:

**Comment by Sorensiim** [comment]
Having recently switched to a single monitor setup, I would absolutely love this feature! 
![20241024_154025](https://github.com/user-attachments/assets/e4b13c65-d00b-4c4e-924a-f20da9b8c653)

**Comment by domferr** [comment]
Hey, quick update for you! I made an initial version and I'd like to share it with you! :star2:  Please test it for a while if you want, any feedback is much appreciated! I need your help to test this extensively so be aware that it may have bugs.

- For GNOME Shell versions 45, 46 and 47: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17541167/tilingshell%40ferrarodomenico.com.zip)
- For GNOME Shell versions from 42 to 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17541165/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)

> To know your GNOME Shell version, run `gnome-shell --version`.
> 
> Extract the downloaded archive. Copy its content to `~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com` directory. You need to reload GNOME Shell afterwards (e.g. by logging out). Then you can enable the extension:
> ```
> /usr/bin/gnome-extensions enable tilingshell@ferrarodomenico.com
> ```

**Comment by domferr** [comment]
:star: Now available in Tiling Shell v14.1!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
