### ISSUE TITLE
[Feature Request] Span window to multiple tiles using only hot-keys

### ISSUE THREAD

**Issue by cracknel** [domferr/tilingshell#120]
It would be awesome to have the "span multiple tiles" feature also available while using hot-keys. I like my screen split into quarters, but sometimes I need a window that spans two tiles vertically and using the keyboard to do that would be great.

Let's say the selected layout is this:
![image](https://github.com/user-attachments/assets/c9ca514e-848d-4e1b-9f3c-2e2c06245d8a)

And I would like to resize window 3 from this
![image](https://github.com/user-attachments/assets/9d3030e8-0163-49f3-8d35-3e2d230896fa)
to this
![image](https://github.com/user-attachments/assets/bf25b1ba-21f2-477d-ab47-ec34f621d4c9)

With the default bindings: super + ⬇️  would move the window to the tile below so it would naturally be super + alt + ⬇️ to span the window to the tile below.

**Comment by domferr** [comment]
Hey! Than you for opening this issue and sharing this idea. I've good news for you: I was already working on this! (#45). It is going to be released with the next update (v13). If you want to try it in advance and give some feedback, I leave here the files. Enjoy!

- GNOME shell version 42, 43 or 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16550098/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME shell version 45 or 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16550099/tilingshell%40ferrarodomenico.com.zip)

**Comment by domferr** [comment]
:star: Now available in [Tiling Shell v13](https://github.com/domferr/tilingshell/releases/tag/13.0.0)!
