### ISSUE TITLE
[Feature Request] Import/export Tiling Shell settings

### ISSUE THREAD

**Issue by domferr** [domferr/tilingshell#122]
**Describe the feature you'd like**
Allow exporting and importing Tiling Shell settings. This could be useful for people who want the same settings on another computer for some reasons.

**Comment by in4matix** [comment]
This would definitely be welcome addition IMO.

**Comment by theoforger** [comment]
Hello! I'd love to give this a shot. I assume the import/export will exclude layouts, since it's already implemented, right?

Great project btw! I recently switched from Forge to this and it runs a lot smoother on my machine

**Comment by domferr** [comment]
> Hello! I'd love to give this a shot. I assume the import/export will exclude layouts, since it's already implemented, right?
> 
> Great project btw! I recently switched from Forge to this and it runs a lot smoother on my machine

Hey! That's nice, this is all yours. Let me know if you need any help or information :smile: 

The goal is to export in JSON format all the settings but not the layouts, as you were thinking about. The idea I had was to somehow export the whole dconf configuration a user have of Tiling Shell. In this way, if we introduce new settings in the future, we don't have to update the code related to exporting all the settings. Let me know what do you think!

**Comment by theoforger** [comment]
Thanks for the response! ❤️ 

> somehow export the whole dconf configuration a user have of Tiling Shell.

I was playing with this idea to spin up a [subprocess](https://gjs.guide/guides/gio/subprocesses.html) and run `dconf dump`. Apparently the dump file is in [KeyFile](https://docs.gtk.org/glib/struct.KeyFile.html) format, and the values are written out in [GVariant Text Format](https://docs.gtk.org/glib/gvariant-text-format.html). Here's an example:
```
[/]
active-screen-edges=true
enable-blur-selected-tilepreview=false
enable-blur-snap-assistant=false
enable-move-keybindings=true
enable-snap-assist=true
enable-span-multiple-tiles=true
enable-tiling-system=true
enable-window-border=false
inner-gaps=uint32 16
last-version-name-installed='13.1'
layouts-json='[{"id":"Layout 1","tiles":[{"x":0,"y":0,"width":0.22,"height":0.5,"groups":[1,2]},{"x":0,"y":0.5,"width":0.22,"height":0.5,"groups":[1,2]},{"x":0.22,"y":0,"width":0.56,"height":1,"groups":[2,3]},{"x":0.78,"y":0,"width":0.22,"height":0.5,"groups":[3,4]},{"x":0.78,"y":0.5,"width":0.22,"height":0.5,"groups":[3,4]}]},{"id":"Layout 2","tiles":[{"x":0,"y":0,"width":0.22,"height":1,"groups":[1]},{"x":0.22,"y":0,"width":0.56,"height":1,"groups":[1,2]},{"x":0.78,"y":0,"width":0.22,"height":1,"groups":[2]}]},{"id":"Layout 3","tiles":[{"x":0,"y":0,"width":0.33,"height":1,"groups":[1]},{"x":0.33,"y":0,"width":0.67,"height":1,"groups":[1]}]},{"id":"Layout 4","tiles":[{"x":0,"y":0,"width":0.67,"height":1,"groups":[1]},{"x":0.67,"y":0,"width":0.33,"height":1,"groups":[1]}]}]'
outer-gaps=uint32 8
overridden-settings='{}'
override-window-menu=true
quarter-tiling-threshold=uint32 40
resize-complementing-windows=true
restore-window-original-size=true
selected-layouts=['Layout 3']
show-indicator=true
snap-assistant-threshold=54
span-multiple-tiles-activation-key=['1']
span-window-left=['<Shift><Alt><Super>s']
span-window-right=['']
tiling-system-activation-key=['0']
top-edge-maximize=false
window-border-width=uint32 3
```

Although GLib does provide tools to parse these formats, I wonder if it's necessary to convert it to JSON?

The options are:
- Use the dump file as-is for import and export
- Parse the file and convert it to JSON for export, and do the reverse for import

Let me know what you think! Or if you prefer it done another way, let me know as well! Thanks again!

**Comment by domferr** [comment]
> Thanks for the response! ❤️
> 
> > somehow export the whole dconf configuration a user have of Tiling Shell.
> 
> I was playing with this idea to spin up a [subprocess](https://gjs.guide/guides/gio/subprocesses.html) and run `dconf dump`. Apparently the dump file is in [KeyFile](https://docs.gtk.org/glib/struct.KeyFile.html) format, and the values are written out in [GVariant Text Format](https://docs.gtk.org/glib/gvariant-text-format.html). Here's an example:
> 
> ```
> [/]
> active-screen-edges=true
> enable-blur-selected-tilepreview=false
> enable-blur-snap-assistant=false
> enable-move-keybindings=true
> enable-snap-assist=true
> enable-span-multiple-tiles=true
> enable-tiling-system=true
> enable-window-border=false
> inner-gaps=uint32 16
> last-version-name-installed='13.1'
> layouts-json='[{"id":"Layout 1","tiles":[{"x":0,"y":0,"width":0.22,"height":0.5,"groups":[1,2]},{"x":0,"y":0.5,"width":0.22,"height":0.5,"groups":[1,2]},{"x":0.22,"y":0,"width":0.56,"height":1,"groups":[2,3]},{"x":0.78,"y":0,"width":0.22,"height":0.5,"groups":[3,4]},{"x":0.78,"y":0.5,"width":0.22,"height":0.5,"groups":[3,4]}]},{"id":"Layout 2","tiles":[{"x":0,"y":0,"width":0.22,"height":1,"groups":[1]},{"x":0.22,"y":0,"width":0.56,"height":1,"groups":[1,2]},{"x":0.78,"y":0,"width":0.22,"height":1,"groups":[2]}]},{"id":"Layout 3","tiles":[{"x":0,"y":0,"width":0.33,"height":1,"groups":[1]},{"x":0.33,"y":0,"width":0.67,"height":1,"groups":[1]}]},{"id":"Layout 4","tiles":[{"x":0,"y":0,"width":0.67,"height":1,"groups":[1]},{"x":0.67,"y":0,"width":0.33,"height":1,"groups":[1]}]}]'
> outer-gaps=uint32 8
> overridden-settings='{}'
> override-window-menu=true
> quarter-tiling-threshold=uint32 40
> resize-complementing-windows=true
> restore-window-original-size=true
> selected-layouts=['Layout 3']
> show-indicator=true
> snap-assistant-threshold=54
> span-multiple-tiles-activation-key=['1']
> span-window-left=['<Shift><Alt><Super>s']
> span-window-right=['']
> tiling-system-activation-key=['0']
> top-edge-maximize=false
> window-border-width=uint32 3
> ```
> 
> Although GLib does provide tools to parse these formats, I wonder if it's necessary to convert it to JSON?
> 
> The options are:
> 
>     * Use the dump file as-is for import and export
> 
>     * Parse the file and convert it to JSON for export, and do the reverse for import
> 
> 
> Let me know what you think! Or if you prefer it done another way, let me know as well! Thanks again!

I believe this is a good idea. JSON format was just for the sake of having a human readable format, however, as in your example, the KeyFile format is human readable too, so it is good as well!

Almost every setting can be then imported safely. The non safe settings are for example the ones related to moving windows using keybindings, because we disable the native setting that GNOME provides since it will clash with ours. In general, when a Tiling Shell setting clashes with a GNOME setting, when the Tiling Shell setting is enabled, the GNOME one is automatically disabled but we remember the native setting with Tiling Shell's `overridden-settings` dconf value (for example if the user had set its own keybindings for moving windows, we put that information into Tiling Shell's `overridden-settings`). This allows us to bring back the previous GNOME settings when the equivalent Tiling Shell setting is disabled or Tiling Shell is disabled/uninstalled.

The overriding is made by [this](https://github.com/domferr/tilingshell/blob/218ca486b622bb4c8023accf4aa364aceec85868/src/settings/settingsOverride.ts#L7) method. The overridden ones are:
- `org.gnome.mutter.edge-tiling` (when Tiling Shell's edge-tiling is enabled/disabled we enable/disable native edge-tiling, https://github.com/domferr/tilingshell/blob/main/src/extension.ts#L99 and https://github.com/domferr/tilingshell/blob/main/src/extension.ts#L243)
- `org.gnome.mutter.keybindings.toggle-tiled-right` (https://github.com/domferr/tilingshell/blob/main/src/keybindings.ts#L128)
- `org.gnome.mutter.keybindings.toggle-tiled-left` (https://github.com/domferr/tilingshell/blob/main/src/keybindings.ts#L137)
- `org.gnome.desktop.wm.keybindings.maximize` (https://github.com/domferr/tilingshell/blob/main/src/keybindings.ts#L151)
- `org.gnome.desktop.wm.keybindings.unmaximize` (https://github.com/domferr/tilingshell/blob/main/src/keybindings.ts#L160)

**Comment by theoforger** [comment]
Thanks for the info! I ran into some confusing behavior while testing the overrides:

- `org.gnome.mutter.edge-tiling` is always turned back on once I disable Tiling Shell's edge-tiling, regardless of what state is stored in `overriden-settings`
- Once the state of `org.gnome.mutter.edge-tiling` is saved inside `overriden-settings`, it never gets updated
- Turning off `enable-move-keybindings` completely clears out `overriden-settings`, including the `org.gnome.mutter.edge-tiling` value.

Am I missing something or could these be bugs? Let me know if you need me to clarify anything ❤️

**Comment by theoforger** [comment]
I made a draft PR just to showcase my idea and what I have done so far. Feel free to give any feedback. Thanks! 🙏

**Comment by domferr** [comment]
Hey, these are surely bugs!

I fixed the following and I'm going to push the changes on the next update's branch:
- *org.gnome.mutter.edge-tiling is always turned back on once I disable Tiling Shell's edge-tiling, regardless of what state is stored in overriden-settings*
- *Turning off enable-move-keybindings completely clears out overriden-settings, including the org.gnome.mutter.edge-tiling value.*

> Once the state of org.gnome.mutter.edge-tiling is saved inside overriden-settings, it never gets updated

I'm not sure, but this bug could be related to the other two. Let's see if it is fixed or not

**Comment by theoforger** [comment]
> > Once the state of org.gnome.mutter.edge-tiling is saved inside overriden-settings, it never gets updated

> I'm not sure, but this bug could be related to the other two. Let's see if it is fixed or not

Just gave it a test. Can confirm it's fixed 👍

**Comment by domferr** [comment]
> > > Once the state of org.gnome.mutter.edge-tiling is saved inside overriden-settings, it never gets updated
> 
> > I'm not sure, but this bug could be related to the other two. Let's see if it is fixed or not
> 
> Just gave it a test. Can confirm it's fixed 👍

That's great! Thank you

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!

**Comment by in4matix** [comment]
Hi, Unfortunately the buttons don't work in Ubuntu 22.04. Can I do some tests from the terminal?

**Comment by domferr** [comment]
Hey @in4matix thank you for reaching out. Which kind of bug do you have? Can you open a new issue about this? Thank you!
