### ISSUE TITLE
outer gaps still present

### ISSUE THREAD

**Issue by Tealk** [domferr/tilingshell#125]
**Describe the bug**
Gaps are still displayed around the window on my notebook's internal monitor, here in the example it is Element. It works on the external monitor.
I think it has to do with the fraction scaling, because the internal monitor is set to 125%.

**To Reproduce**
1. install tiling shell
2. set outer gaps to 0
3 arrange windows

**Screenshots**
![Screenshot from 2024-08-17 12-22-33](https://github.com/user-attachments/assets/cbcf7190-d475-4a55-a831-e43d8e3101c5)

**Information (please complete the following):**
 - Tiling Shell version: v12.2
 - GNOME version: GNOME Shell 46.4

**Comment by domferr** [comment]
Hi @Tealk, thank you for sharing this bug and sorry for the late response. Could you tell me if the bug arises without fractional scaling? Thanks!

**Comment by Tealk** [comment]
Unfortunately I no longer have the same system installed, distrohopping <3
But without it, it has attached itself to the edge.
