### ISSUE TITLE
[Feature Request] Add drag threshold before a tiled window is unsnapped

### ISSUE THREAD

**Issue by jibsaramnim** [domferr/tilingshell#126]
**Describe the feature you'd like**
It would be nice if at all possible if there was a (customizable) threshold that would keep windows from being snapped out of their place if one clicks their titlebar while also slightly (and inadvertently) moving the mouse a pixel or two.

**Additional context**
Whenever I want to select a tiled window, I must also slightly move my mouse or trackball a bit too, which immediately removes the window from its snapped state. I know this is technically user error in that I shouldn't be moving the mouse at all when clicking down, but it's a very small amount of movement I must inadvertently make, that in other situations (like selecting a file in Nautilus, or a tab in Firefox) doesn't really cause any issues as there's a bit of a threshold in those cases before a "drag" condition is triggered.

For me personally it would be more than enough if that threshold is hard-coded like it is with the aforementioned Nautilus and Firefox examples, but I can also imagine that some people might want this a toggle-able or otherwise adjustable setting — if it's possible to implement at all, of course.

Thank you so very much for making this! I'm new to using your extension, but I love what I'm seeing so far. Very nice!

**Comment by domferr** [comment]
Hey, thank you for this suggestion! This seems to be a nice addition, hope to work on this soon!

**Comment by domferr** [comment]
Hey, quick update for you! This is going to be released with the next upcoming update (v14)! :soon:

**Comment by jibsaramnim** [comment]
That's fantastic news, thank you so much!

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!
