### ISSUE TITLE
[Feature Request] A button to save current layout

### ISSUE THREAD

**Issue by in4matix** [domferr/tilingshell#128]
Also "rememer" which App windows use this layout. Perhaps the ability to assign titles to layouts, e.g. Graphic Design, JS Coding, etc. for various frequently used workflows.

**Comment by domferr** [comment]
Hey, thank you for this suggestion! Were you thinking about something like this? #100

**Comment by in4matix** [comment]
Hey, hope you doing well? 

> Were you thinking about something like this? https://github.com/domferr/tilingshell/issues/100

Yes pretty much, but I was thinking launching the saved layouts from the TS menu, perhaps with a expandable menu at the bottom with all the saved layout listed there. Something like this maybe:

![Mockup](https://github.com/user-attachments/assets/4a0a1c7b-be9b-4757-b285-645babe4f5fc)
