### ISSUE TITLE
Snap assistant unfolds too early

### ISSUE THREAD

**Issue by Questy4tw** [domferr/tilingshell#129]
**Describe the feature you'd like**
Right now, the hitbox for the snap assistant is larger than the actual black bar, which sometimes causes it to unfold itself unintentionally when dragging windows.
I think it would be better, that the assistant only unfolds itself when actually touching the bar with the mouse and window. Or maybe an option for this offset

**Additional context**
You can see it in the already provided clip of this project. -> snap_assistant.webm

**Comment by domferr** [comment]
Hey, thank you for opening this! This is covered by the setting "Snap Assistant threshold":

<p align="center">
<img src="https://github.com/user-attachments/assets/e0107c9e-6460-4ee3-814d-cfac3b10b9df" width=480 />
</p>

If you set it to 0, the assistant will unfold when actually touching it, without any offset.

[video](https://github.com/user-attachments/assets/f4584815-821b-4c20-b3d4-c706cc1e869b)
