### ISSUE TITLE
[Feature Request] Add a deactivation key or an option to invert the activation key

### ISSUE THREAD

**Issue by gianjohansen** [domferr/tilingshell#130]
**Describe the feature you'd like**
Hi, thanks for the extension, it's really well integrated into gnome.

 I'd like to have mouse tiling on permanently (currently implemented by selecting the "None" option for activation key) but also have a key which disables the tiling system when held down. Tiling is what I want for 95% of my windows but for the other 5% there's no way to precisely place them if None is selected as activation key.

This could be a separate deactivation key or a toggle saying something like 'Invert activation key behaviour: _Tile without a key when moving a window, hold the activation key to disable it_'.

**Comment by domferr** [comment]
Hey, thank you for opening this issue! This is interesting, however I'm not sure this is feasible. I'll do some research!

**Comment by domferr** [comment]
:star: Now available in Tiling Shell v14.1!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
