### ISSUE TITLE
[Feature Request] Draw a border on the currently focused window

### ISSUE THREAD

**Issue by domferr** [domferr/tilingshell#132]
**Describe the feature you'd like**
It would be nice to have a customizable border around the focused window. Use a different default color if the window is tiled or not.

**Additional context**
![image](https://github.com/user-attachments/assets/d66fced7-6ca7-46a2-ae9f-9d36d448febf)

**Comment by domferr** [comment]
Quick update :partying_face:

[Screencast from 2024-08-31 15-48-45.webm](https://github.com/user-attachments/assets/077fbe2a-a64f-4377-af61-e01002c1f902)

**Comment by domferr** [comment]
The idea is to allow to customize it, so you can choose if you want the rounded border or not.

<p align="center">
<img src="https://github.com/user-attachments/assets/c6596992-f05e-429a-91e5-3ec01ad71f60" width=300 />
<img src="https://github.com/user-attachments/assets/95b9f7a4-ace1-4410-8003-ebcbe6727533" width=300 />
</br>
:arrow_double_up:  With rounded borders | Without rounded borders :arrow_double_up:  
</p>

**Comment by Peter-Ries** [comment]
Very good idea and implementation.
Now missing the adjustment of color.
As GNOME 47 introduces custom accent colors it would be great to pick that one instead of "Ubuntu-orange".

**Comment by domferr** [comment]
> Very good idea and implementation. Now missing the adjustment of color. As GNOME 47 introduces custom accent colors it would be great to pick that one instead of "Ubuntu-orange".

I agree with you!
