### ISSUE TITLE
Export layouts button not working

### ISSUE THREAD

**Issue by in4matix** [domferr/tilingshell#134]
**Describe the bug**
Export layouts button not working. When the button is selected nothing happens.

**Information (please complete the following):**
 - Tiling Shell version: Latest version from Gnome Shell Extension Website.
 - GNOME version: 42.9 (Ubuntu 22.04 LTS)

**Comment by domferr** [comment]
Hey thank you for reporting this issue! I hope to test on GNOME 42.9 soon to try to reproduce the problem

**Comment by lorenx** [comment]
Same version, same issue here.
The _Import layouts_ button either, none of them opens any dialog.

Thank you anyway, it's a wonderful and extremely useful piece of software.

**Comment by domferr** [comment]
Hey guys, quick update for you. I finally found a way to fix it. This is going to be released in the next upcoming release (v14) of Tiling Shell :soon: !

**Comment by in4matix** [comment]
That's good news! Thanks!

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!

**Comment by in4matix** [comment]
Hi, Unfortunately the buttons still don't work. Can I do some tests from the terminal?
