### ISSUE TITLE
Indepent workspace tiles

### ISSUE THREAD

**Issue by diegoprestegui** [domferr/tilingshell#137]
**Describe the feature you'd like**
A clear and concise description of what you want to happen (Ex. it would be nice to have [...]).
Is your feature request related to a problem? Please describe (Ex. I'm always frustrated when [...])

I would like to have different tiles layouts for different workspaces.

**Additional context**

**Comment by domferr** [comment]
Hey thank you for sharing this! We got already another issue about it where we did some brainstorming too, see you there! #118

**Comment by domferr** [comment]
Hey, quick update for you! Check the issue #47 for an initial version of this! Thank you
