### ISSUE TITLE
[Feature Request] Add keybinding to move window to center

### ISSUE THREAD

**Issue by danielbmeireles** [domferr/tilingshell#139]
I want to suggest the implementation of a "Move Window to Center" functionality, similar to the functionality of the same name found in the Ubuntu Tiling Assitant:

![Screenshot from 2024-09-12 09-33-02](https://github.com/user-attachments/assets/521f3c14-dfb6-4ff2-b149-76f8db32cb21)

**Comment by domferr** [comment]
Hey, thank you for this suggestion! I think it is a nice one :smile:

**Comment by thyttan** [comment]
What exactly does Move Window to Center do in Ubuntu Tiling Assitant?

Does it move the window to one of the areas of the tiling layout that are the most centered? Or does it work without regard to the tiling layout?

**Comment by danielbmeireles** [comment]
> What exactly does Move Window to Center do in Ubuntu Tiling Assitant?
> 
> Does it move the window to one of the areas of the tiling layout that are the most centered? Or does it work without regard to the active tiling layout?

The option moves the window to the center of the screen, regardless of the tiling layout.

**Comment by domferr** [comment]
Hey, quick update. This is coming soon in the next Tiling Shell update :partying_face: 

[Screencast from 2024-10-06 12-09-14.webm](https://github.com/user-attachments/assets/4be3e838-348c-4c9a-826b-7e3db2035b7f)

**Comment by danielbmeireles** [comment]
You, sir, are a rockstar!

**Comment by danielbmeireles** [comment]
Works like a charm! Thank you!
