### ISSUE TITLE
[Feature Request] Add the ability to cancel the tiling when dragging a window and pressing right click.

### ISSUE THREAD

**Issue by demencia89** [domferr/tilingshell#141]
When tiling is enabled without a keypress, every time you move a window it is rezised and moved to the area where the mouse is hovering. It'd be super useful to be able to cancel this by pressing the right click button, allowing you to freely move this window and not being tiled. Thanks! Please let me know if the request is not clear so I can rephrase, english is not my native language.

**Comment by domferr** [comment]
Hey, thank you for opening this issue! This is interesting, however I'm not sure this is feasible. I'll do some research!

**Comment by demencia89** [comment]
I thought it could be tricky, but hopefully it's feasible as it'd finally have my workflow complete on linux! Thank you for making this extension 🙏 !!

**Comment by domferr** [comment]
:star: Now available in Tiling Shell v14.1!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>

**Comment by demencia89** [comment]
ooh myyyy god, thank you so much dude, I've wanted this for so long! you're the man!
