### ISSUE TITLE
Cannot move a window to the right tile (3) when using three tiles 1|2|3

### ISSUE THREAD

**Issue by db-tech** [domferr/tilingshell#143]
**Describe the bug**  
I have three tiles arranged in the order 1 | 2 | 3.  
I am unable to move a window to tile 3 from tile 2. Moving windows between tiles 1 and 2 works as expected (e.g., 1 → 2, 3 → 2 → 1), but moving from tile 2 to tile 3 does not work.

**To Reproduce**  
1. Move a window to tile 2.
2. Press `Super + Right` to move the window to tile 3.

**System Information**  
- **Tiling Shell version**: v13.0  
- **GNOME version**: GNOME Shell 46.4

**Comment by db-tech** [comment]
Sure,

I got Inner gaps 3 and Outer gaps 1

**Comment by domferr** [comment]
> Sure,
> 
> I got Inner gaps 3 and Outer gaps 1

But good news and bad news: I can reproduce your problem if I set the same gaps. Hope to fix this soon :soon:

**Comment by domferr** [comment]
Hey @db-tech can you test whether this is now fixed? :smile: I'll share the update, thank you:

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17178665/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45, 46 and 47: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17178666/tilingshell%40ferrarodomenico.com.zip)

___

If you don't know how to install, here it is a little guide for you. You need to perform the following steps: overwrite the files into `.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com` with the ones in the archive I shared, then log out and log in (or restart the system).

**Comment by db-tech** [comment]
Looks good, Nice work !
