### ISSUE TITLE
[Feature request] Display screen index in layout dialog

### ISSUE THREAD

**Issue by vinchatl** [domferr/tilingshell#147]
I'm currently using two identical monitors and it works pretty well, but unfortunately that mean they have the same name in the layout dialog so I can't distinguish which is which:

![image](https://github.com/user-attachments/assets/5b5219b2-449f-4e51-925e-d75d255923cb)

If you can get this info, it would be nice to also display the screen number like in GNOME settings (respecting the number displayed in the settings of course, to avoid any confusion).

**Comment by domferr** [comment]
Hey @vinchatl thank you for this suggestion. There were some work going on #81 but we didn't finish, yet. Hope to implement this soon!

**Comment by vinchatl** [comment]
Thanks for the feedback ! I'll close this issue as you're already tracking the request and working on a solution. :)
