### ISSUE TITLE
Chromium-based browsers restore their size on clicking their header bar

### ISSUE THREAD

**Issue by bsdson** [domferr/tilingshell#148]
**Describe the bug**
With "Restore window size" setting turned on, a tiled "chrome app" window might restore its size on clicking its header bar.

**To Reproduce**
1. Create a Chrome app window. (*. see below for more info)
2. Resize the window to a size different from 1/4 of the screen.
3. Drag the window to the screen corner to make it as big as 1/4 of the screen.
4. Click on another window.
5. Click on the Chrome app window's header bar.
6. Check the window size.

**Screenshots**
NA

**Information (please complete the following):**
 - Tiling Shell version: v13.1
 - GNOME version: 46

**Additional context**
*. How to create a Chrome app window.
(For example)
1. open keeps.google.com in Chrome
2. click the icon at the right of the address bar to make this web page a chrome app.
3. after this, you will be opening the web page as a standalone window, which feels like its a normal application.
PS. the height of the header bar will be shorter than a normal window.

![Screenshot from 2024-10-04 09-43-02](https://github.com/user-attachments/assets/7f67b90b-2a8a-4f98-9c77-4cab49a82bc9)

**Comment by DarkGhostHunter** [comment]
This.  It's pretty annoying on all browser that use tabs, like... all browsers. The only workaround is to disable resize on title.

Resizing should work only when the window is moved away from the grid, and maybe trigger after the window moves an amount of pixels.

**Comment by domferr** [comment]
Hey guys, thank you for reporting this issue. I'm not using a chrome-based browser, so I completely missed this bug. Indeed, performing a long click on the window has a completely different behavior on firefox:

[Screencast from 2024-10-06 17-43-53.webm](https://github.com/user-attachments/assets/04022f26-dd7c-401a-85d9-d7e0a61d098b)

Doing a long left click on firefox's window doesn't trigger a window grab, while it does for chromium (and all chrome-based browsers then...). Hope to fix this soon :soon:

**Comment by DarkGhostHunter** [comment]
Can be detected the grab length? I think a solution would be to proceed with the resize only if the grab moves a certain amount of pixels. This way, clicking the title bar regardless of the app won't trigger a resize.

**Comment by domferr** [comment]
Hey, a quick update for you. The fix to this bug is going to land with the next upcoming update (v14)! :soon:

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!
