### ISSUE TITLE
[Feature Request] Window border color selection setting 

### ISSUE THREAD

**Issue by mateHD** [domferr/tilingshell#149]
The Window border is red now, a color selector would be great.

**Comment by domferr** [comment]
Hey I've good news for you, this is currently under development :wink:

**Comment by rubin55** [comment]
Will this use the [new accent color stuff(https://release.gnome.org/47/)] that's available in Gnome 47?

**Comment by domferr** [comment]
> Will this use the [new accent color stuff](https://release.gnome.org/47/) that's available in Gnome 47?

Hey sorry for the late response. Not yet, but instead you can pick any color you want. In the future, I'll put a button or some other behavior to automatically pick the accent color

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!
