### ISSUE TITLE
[Feature Request] Customize preview animation speed

### ISSUE THREAD

**Issue by fabijoe92** [domferr/tilingshell#150]
Hello there.

Excellent GNOME extension!

I feel that the animation of the snapping preview (blue area) is a little too fast.

Maybe an option to tune that down a little would be fantastic. Or maybe the option to just show the blue area.

Keep up the fantastic work!

Cheers!

[Bildschirmaufzeichnung vom 2024-10-05 23-23-25.webm](https://github.com/user-attachments/assets/fac15286-e866-4d75-b8c1-45b173f76a41)

**Comment by domferr** [comment]
Hey thank you for sharing. Customizing animations speed will be available in one of the next updates. Hope to implement it soon! :soon:

**Comment by domferr** [comment]
Hey, quick update! Enabling/disabling and customizing animations is landing on next release! :star:

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!
