### ISSUE TITLE
Assign layout for individual workspaces

### ISSUE THREAD

**Issue by Sorensiim** [domferr/tilingshell#153]
**Describe the feature you'd like**
First off, thank you for your work. Love the tiling shell extension! 

I use it at work on my 3x27" 1440p monitors but also at my desk at home, with a 32" 4K monitor. The latter setup has me swiping between Gnome workspaces and I'd love to be able to assign different layout to different workspaces just like I can assign different layouts to different monitors.

**Comment by domferr** [comment]
Hey, I'm so happy you are loving Tiling Shell! Thank you for this suggestion. We did some brainstorming here #118, hope to implement this soon!

**Comment by domferr** [comment]
Hey, quick update for you! I made an initial version and I'd like to share it with you! :star2:  Please test it for a while if you want, any feedback is much appreciated! I need your help to test this extensively so be aware that it may have bugs.

- For GNOME Shell versions 45, 46 and 47: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17541167/tilingshell%40ferrarodomenico.com.zip)
- For GNOME Shell versions from 42 to 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17541165/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)

> To know your GNOME Shell version, run `gnome-shell --version`.
> 
> Extract the downloaded archive. Copy its content to `~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com` directory. You need to reload GNOME Shell afterwards (e.g. by logging out). Then you can enable the extension:
> ```
> /usr/bin/gnome-extensions enable tilingshell@ferrarodomenico.com
> ```

**Comment by domferr** [comment]
:star: Now available in Tiling Shell v14.1!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
