### ISSUE TITLE
[BUG] `Move window to tile above` maps to `Move window to the center`

### ISSUE THREAD

**Issue by thyttan** [domferr/tilingshell#156]
**Describe the bug**
The keyboard shortcut for `Move window to tile above` ( I map to `Alt + Super + k`) triggers the `Move window to the center` function instead.

Once moved to the center I can't move it by keyboard shortcuts at all - it's locked in place. But if I drag it with the cursor that works and it "unlocks" the keyboar shortcuts again.

**To Reproduce**
1. Open a window on a workspace.
2. Use the `Move window to tile above` keybinding.
3. Notice the window snap to center of screen. (ERROR!)
4. Try using keybindings to move the window - doesn't work any longer.
5. Drag the window around by cursor.
6. Now use keybindings to move the window around - now it works again!

**Screencapture**

https://github.com/user-attachments/assets/852c910b-5aa9-4b82-af82-ceb37bd56320

**Information (please complete the following):**
 - Tiling Shell version: 14
 - GNOME version: 46.6

**Additional context**

![image](https://github.com/user-attachments/assets/a70584cb-2cc6-49ce-bd23-60d318d9cca5)

**Comment by domferr** [comment]
Hey @thyttan thank you for spotting this bug. I updated the release's attached files with a fix. Can you confirm the bug is solved? Thanks!

**Comment by thyttan** [comment]
Yes - that fixed it!

A heads up - I'm about to file another bug report about moving windows with keybindings to move windows right <-> left on an even 2x2 tiling layout.
