### ISSUE TITLE
[BUG] Keybinding move left/right moves diagonally on even 2x2 tiling layout

### ISSUE THREAD

**Issue by thyttan** [domferr/tilingshell#157]
**Describe the bug**
On an even 2x2 tiling layout using keybindings to move window horizontally moves them diagonally instead.

**To Reproduce**
1. On an empty workspace select an even 2x2 tiling layout.
2. Launch a terminal window.
3. Use keybinding `Move window to right tile` (I use `alt + super + L`).
4. Window snaps to the top left. *(Up for discussion if this is expected or unexpected behaviour)*
5. Use keybinding `Move window to right tile` again.
6. Window snaps to top right.
7. Use keybinding `Move window to the left tile`.
8. Window snaps to bottom left. **(Unexpected!)**
9. Use keybinding `Move window to right tile` again.
10. Window snaps to top right. **(Unexpected!)**

The repro above is what I did in the screencast below.

**Screencast**

https://github.com/user-attachments/assets/b22e3ca5-9879-4b86-a32e-6fc865416027

**Information (please complete the following):**
 - Tiling Shell version: 14 (after you fix of [#156](https://github.com/domferr/tilingshell/issues/156))
 - GNOME version: 46.6

**Additional context**
![image](https://github.com/user-attachments/assets/dc92ccb6-ef62-4248-93e1-8cf38efbfa66)

**Comment by domferr** [comment]
Hey thanks a million for reporting this! I'm still improving the algorithm behind all of this, so it's great to have your feedback. I made some changes, would you like to give it a try?

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17518522/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45, 46 and 47: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17518525/tilingshell%40ferrarodomenico.com.zip)

**Comment by thyttan** [comment]
Yes - that did the trick! Thanks!

**Comment by domferr** [comment]
Great! :star:

**Comment by thyttan** [comment]
While we're at it - I'll open another issue for a similar, but less clear behaviour which I feel is unexpected but maybe is expected.

**Comment by domferr** [comment]
Ok thank you! Can you also check whether the issue occurs in the version I shared you above?

**Comment by thyttan** [comment]
Yes it does :) But again - it's not as clear cut unexpected as this issue was.
