### ISSUE TITLE
Use keybinding to move to new tile at same edge after switching layout

### ISSUE THREAD

**Issue by thyttan** [domferr/tilingshell#159]
**Describe the bug**
If a window was tiled to a screen edge in one layout and the layout is changed, using `Move window to right/left tile` keybinding towards the same edge does not resize it to the new layout.

**To Reproduce**
1. Be on an empty workspace.
2. Open a window.
3. Snap the window to the right screen edge using keybinding `Move window to right tile` (repeat if needed).
4. Change the tiling layout with different size tiles along the right screen edge compared to current layout.
5. Try snapping to the new tile along the right screen edge with keybinding `Move window to right tile`.
6. Notice nothing happens **(Unexepected! I'd have expected the window to resize to the new layouts right edge tile)**
7. Use keybinding `Move window to left tile` to move window to new layout.
8. Use keybinding `Move window to right tile` to move window to the new layouts right edge tile.

The repro above is what I do in the screencast below.

**Screencast**

https://github.com/user-attachments/assets/8b4754a5-3a1f-4bf9-8d15-296ef33d913c

**Information (please complete the following):**
 - Tiling Shell version: 14 (with changes from [#157](https://github.com/domferr/tilingshell/issues/157#issuecomment-2437180879))
 - GNOME version: 46.6

**Additional context**
![image](https://github.com/user-attachments/assets/ccb37558-e6b9-4dd2-aec2-f72f16b46008)

**Comment by domferr** [comment]
Heheheh! I'm not used to move windows using keybindings, so your testing is very welcome, thanks once again. Changing a layout currently is never taken into consideration, so you have that kind of behavior. I'll keep this open, to remember to improve the whole algorithm!

A question for you: how much do you believe it is important to support such layout changes? Thanks once again!

**Comment by thyttan** [comment]
> how much do you believe it is important to support such layout

It's something that would be nice to see handled eventually. Not as important as e.g. #157 was 😇

**Comment by domferr** [comment]
Hey, check this out! 
[tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17747251/tilingshell%40ferrarodomenico.com.zip)

I made come improvements and this should now be possible :heart:

**Comment by thyttan** [comment]
Nice - thanks! Works like I'd expect now!

**Comment by domferr** [comment]
Now available in Tiling Shell v15.0
