### ISSUE TITLE
Missing italian translations

### ISSUE THREAD

**Issue by AlexFalappa** [domferr/tilingshell#161]
**Describe the bug**
Some italian translations are missing

**To Reproduce**
1. Open Tiling Shell settings dialog
2. Scroll down to the import/export settings

**Screenshots**
![image](https://github.com/user-attachments/assets/457e3ab3-eac7-45f9-8d19-5af67dcc4337)

**Information (please complete the following):**
 - Tiling Shell version: v14
 - GNOME version: 46

**Additional context**
I opened PR #160 potentially fixing this issue

**Comment by domferr** [comment]
Hey, thank you for reporting this. I was aware of this and I already prepared a fix. I hope to publish an update soon!
