### ISSUE TITLE
New default layout

### ISSUE THREAD

**Issue by taishingi** [domferr/tilingshell#162]
Can you add this layout ?

### Possibilities

![Capture d’écran du 2024-10-26 12-01-00](https://github.com/user-attachments/assets/db49c746-ab1c-4add-af68-3c54ce3b03aa)

![Capture d’écran du 2024-10-26 12-00-27](https://github.com/user-attachments/assets/6c3a33f7-b4a9-46d9-b67f-dae5084a8da4)

![Capture d’écran du 2024-10-26 11-59-18](https://github.com/user-attachments/assets/d296cfe5-55d0-4b8d-8de6-08ee9d375118)

![Capture d’écran du 2024-10-26 11-58-56](https://github.com/user-attachments/assets/0d403be7-d8be-4e2a-8646-ae45988cabc2)

![Capture d’écran du 2024-10-26 11-58-16](https://github.com/user-attachments/assets/68dda353-51f3-4cb5-abc2-f3d73dc04160)

### Width x Height

![Capture d’écran du 2024-10-26 11-49-20](https://github.com/user-attachments/assets/e883bcda-7b1a-4970-8e3a-14414c5c5c5a)

![Capture d’écran du 2024-10-26 11-49-45](https://github.com/user-attachments/assets/0fa0a9aa-bd2c-4727-bbbc-54c2966359bd)

![Capture d’écran du 2024-10-26 11-50-11](https://github.com/user-attachments/assets/269299ee-a6c6-4f17-959b-8a28d0ceac78)

![Capture d’écran du 2024-10-26 11-51-01](https://github.com/user-attachments/assets/25137543-ee6f-4431-8f34-84b5e8b08982)

![Capture d’écran du 2024-10-26 11-51-29](https://github.com/user-attachments/assets/10fe804c-a93f-456b-9056-6b072f48b9ba)

![Capture d’écran du 2024-10-26 11-52-00](https://github.com/user-attachments/assets/e50ba612-dd4a-43c3-903e-4d47251ec322)

**Comment by taishingi** [comment]
![Capture d’écran du 2024-10-26 12-39-55](https://github.com/user-attachments/assets/abf795b0-986e-493e-bff3-5e7dedbacc7e)


![Capture d’écran du 2024-10-26 12-44-14](https://github.com/user-attachments/assets/80903492-23b9-42fe-b44f-f23e5a71e03b)

**Comment by domferr** [comment]
Hey! There are currently 4 default layouts and adding more would end up wasting a lot of space. Luckily people can import layouts and share between them

**Comment by taishingi** [comment]
ok i understand
