### ISSUE TITLE
Facilitate the creation of responsive and flexible layouts

### ISSUE THREAD

**Issue by taishingi** [domferr/tilingshell#163]
I suggest adding the following units
 - percentages
 - px
 - vh
 - vw
 - em
 - rem

This new unit, combined with inputs can be  improve the user experience

User we can say "create a horizontal block to take 25% of the screen,  align middle and create two new block with the rest"

Ideas: align (middle,top,right,left...), witdh & height ( 50 %, 5 hw...)

Implement a flexible grid system to facilitate alignment of elements and create balanced layouts.

Reusable components library: Make available a library of pre-defined components to speed up development.

Best regard

**Comment by domferr** [comment]
Hey, follow #105 with updates about this :soon:
