### ISSUE TITLE
[Feature Request] Allow holding a key to stop tiling a window

### ISSUE THREAD

**Issue by 1amnotmad** [domferr/tilingshell#164]
**Describe the feature you'd like**
I would like an option to hold a key down to *not* a window when I move it.

**Additional context**
I have my windows tile with no key, but no and then I'd like to move a floating window without it tiling. To do this, seems like having an option to hold  key to prevent it from tiling would work well.

Thank you!

**Comment by domferr** [comment]
Hey, I believe this would be a nice addition! Hope to work on this soon

**Comment by domferr** [comment]
Hey, this is going to be released with the next update :soon:

**Comment by domferr** [comment]
:star: Now available in Tiling Shell v14.1!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
