### ISSUE TITLE
[Feature Request] Automatically tile newly created windows

### ISSUE THREAD

**Issue by domferr** [domferr/tilingshell#169]
Coming soon in Tiling Shell, **automatic tiling**! When a window is created, it is automatically moved to the best tile according to where other windows are tiled and the current layout.

The feature is in its early stages, it follows the currently selected layout to pick the best tile for newly created windows. The setting can be enabled/disabled from the extension's preferences (disabled by default). The _best tile_ is the vacant tile nearest to the center of the screen. Check this out!

[automatic_layout](https://github.com/user-attachments/assets/76abc53f-2c6d-47ab-bee3-bbcdd946f2a1)

Give it a try, any feedback would be much appreciated :heart:

- For GNOME Shell versions 45, 46 and 47: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17571734/tilingshell%40ferrarodomenico.com.zip)
- For GNOME Shell versions from 42 to 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17571736/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)

To know your GNOME Shell version, run `gnome-shell --version`.

Extract the downloaded archive. Copy its content to `~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com` directory. You need to reload GNOME Shell afterwards (e.g. by logging out). Then you can enable the extension:
```
/usr/bin/gnome-extensions enable tilingshell@ferrarodomenico.com
```

**Comment by thyttan** [comment]
Cool - thanks!

Some initial feedback:
If an app was previously maximized it will launch maximized again and not be fitted into the *best tile*. When the windows is later unmaximized it goes into a floating state.

I'm not sure what is the desired behaviour, but my initial expectation was that the window should fit into the *best tile* - regardless of the state it was in when it was closed before. 

Another solution may be to let it go to maximized state like it does now. But then when it is unmaximized it would be fitted to the *best tile*?

**Comment by domferr** [comment]
Hey @thyttan thank you so much for testing this out!

This is completely intended: when a window opens maximized, I assume you are used to use it that way so I don't apply any automatic tiling. The suggestion to automatically tile when a window is unmaximized is great, thank you!

Maybe, in a later update, it could be nice to have a setting to specify whether or not automatically tile maximized windows.

**Comment by domferr** [comment]
Here it is! When windows are unmaximized they are now automatically tiled:

- For GNOME Shell versions 45, 46 and 47: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17571734/tilingshell%40ferrarodomenico.com.zip)
- For GNOME Shell versions from 42 to 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17571736/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)

**Comment by thyttan** [comment]
Thanks - that's very nice I think!

However, it leads me to a new edge case.

I may have a window that I want floating for the most part, but maximize at times. Then I'd want the window to return to the position it had before it was maximized.

E.g:
1. open a window which is auto tiled.
2. reposition it as a floating window (and maybe add the `Always on top` window property).
3. maximize the window.
4. unmaximize the window, having it return to its floating (+ potentially `Always on top`) state.

So the difference to the current situation would be that unmaximizing is done slightly differently depending of if (a) the window was initialized in maximized state, or if (b) it was only maximized at a later point in the windows life time.

For (a) it would always be fitted to the *best tile*. For (b) it would be returned to the state it had just before being maximized.

If this is not easy to accomplish I'd say it's not very important - but it would be nice :)

### Screencast

https://github.com/user-attachments/assets/c0a07c36-4357-4665-b31b-ed16de939f04

**Comment by joaocandre** [comment]
One aspect of this that I think could be improved is to configure whether auto-tiling only applies when empty tiles are available,  or for all new windows, tiling them over the oldest used tile (or something along those lines).
Currently it seems that newer windows aren't auto-tiled when all tiles are already being used.

**Comment by thyttan** [comment]
@joaocandre Your idea seems adjacent to https://github.com/domferr/tilingshell/issues/165 - at least to me! :)

**Comment by joaocandre** [comment]
Certainly, although my take was much more simplistic - just extending the auto-tiling feature to all new windows, regardless of the number of windows in each tile.
A way to cycle through / deal with overlapping windows would pair well with it.
