### ISSUE TITLE
Window border bug

### ISSUE THREAD

**Issue by jackthenewbie** [domferr/tilingshell#171]
**Describe the bug**
Whenever border color is enable, plug in or unplug a new monitor will leave all the border popup on top

**To Reproduce**
1. Enable "Window border"
2. Plug a new monitor or unplug one (If you have >2)

**Screenshots**
![image](https://github.com/user-attachments/assets/0c03a590-f56b-471d-8b66-0f831f4e5108)

**Information (please complete the following):**
 - Tiling Shell version: v14
 - GNOME version: 46

**Additional context**
That or maybe this just my monitor, I'm using "Viture XR glasses" as my monitor (you can think of it as second monitor for my laptop), I haven't got any chance to test with other monitor yet, but if this is just me and my monitor you can close this issue. This can quickly solve by re-enable "Window border", but will happen again if I plug or unplug the monitor.

**Comment by domferr** [comment]
Hey thank you for sharing this bug! I'm having the same once in a while and came up with a solution. This is a version with the bugfix, if you try it let me know if it solves the problem. Thanks!

[tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17584134/tilingshell%40ferrarodomenico.com.zip)

**Comment by domferr** [comment]
:star: Now available in Tiling Shell v14.1!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
