### ISSUE TITLE
Border overlaps with window if it spawns overflows its initial one

### ISSUE THREAD

**Issue by BigBoyBarney** [domferr/tilingshell#174]
**Describe the bug**
If a (rectangular) window spawns another popup-style window or dialogue, the border will draw over it.

**To Reproduce**
1. Open Nautilus on Gnome 47
2. Select a folder that's relatively close to the bottom of the window (see screenshots)
3. Attempt to rename folder

**Screenshots**
Nautilus
![image](https://github.com/user-attachments/assets/1bb06466-6134-45a4-9c7a-0a7d087ce8ca)

Zen Browser
![image](https://github.com/user-attachments/assets/6500f6d0-2e56-48d8-8db0-5c1472730c1f)

**Information (please complete the following):**
 - Tiling Shell version: 33
 - GNOME version: 47

Thanks, love the extension! <3

**Comment by domferr** [comment]
Hey, thank you for sharing this. Unfortunately this is a common problem of all the GNOME extensions who provide a border around the focused window, Tiling Shell included. This is due to some GNOME limitations that doesn't allow developers to draw that border without workarounds

**Comment by BigBoyBarney** [comment]
Ah well, understandable! Thanks again!
