### ISSUE TITLE
Unable to exit layout editing if the tray icon is disabled

### ISSUE THREAD

**Issue by domferr** [domferr/tilingshell#18]
## How to reproduce the problem
The options to save or cancel layout editing can be accessed from the tray icon. If the tray icon is disabled from the preferences, there isn't any way to save a new layout or cancel the editing.

![image](https://github.com/domferr/tilingshell/assets/14203981/cdf7fa0a-d250-47f4-a61a-fdc1e5745651)

## Good First Issue

This is a good first issue to start contributing to an open source project or if you have never contributed to a GNOME extension. If you are interested, comment here with any question you have, I'm happy to guide you through the source code and provide any help needed!

When contributing to this repository, please first discuss here before making a change, so we are sure we are not duplicating efforts.

**Comment by tomaszk8266** [comment]
My ideas:
 - A floating window containing these options
 -  ESC key to exit without saving and ENTER to save
 -  Showing the indicator even if it's disabled in edit mode

**Comment by domferr** [comment]
Hi @tomaszk8266, thank you for sharing your ideas! I was thinking about the third option too, which is also the fastest way to fix issue and a good UX imho

**Comment by domferr** [comment]
:heavy_check_mark: Bug fixed in version 8.0!
New version will be available on GSE soon and can be already downloaded from GitHub releases.
