### ISSUE TITLE
Untile Hotkey Fails After Tiling, Untiling, and Re-Tiling Window

### ISSUE THREAD

**Issue by SuiziM** [domferr/tilingshell#180]
After using hotkeys to move or span a window across tiles and then un-tiling it, the "Untile focused window" hotkey fails to work after re-tiling.

**To Reproduce**

1. Use hotkey to move a window to a specific tile or span it across tiles.
2. Use the hotkey to "Untile focused window."
3. Use a tiling hotkey from step 1 again.
4. Try to use the "Untile focused window" hotkey—notice that it no longer works.

**Screenrecording**

![Screenrecording](https://github.com/user-attachments/assets/b2f104af-be3b-4da3-8c23-fd982f0bdcd3)

Super + Left = Move window to left tile
Super + Delete = Untile focused window

**Information**

    Tiling Shell version: 14.1
    GNOME version: 47.1
    
Thanks for all the great work on Tiling Shell!

**Comment by domferr** [comment]
Hey @SuiziM thank you for reporting this issue! I made some tests and I can reproduce the problem. I made a bugfix, let me know if it works and if it doesn't create other problems :smile: 

[tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17680731/tilingshell%40ferrarodomenico.com.zip)

**Comment by SuiziM** [comment]
Thanks for the quick turnaround! This mostly addresses the issue; I’ve only noticed two edge cases, which might be harder to reproduce. One might not even be related to this. 

### First Issue 
Occurs when positioning the window too close to a screen border, then tiling, untiling, and attempting to tile in the direction of the near screen border.

**Steps To Reproduce**

1. Position the window near a screen border.
2. Tile the window using hotkeys.
3. Untile the window using hotkeys.
4. Attempt to tile the window toward the near screen border—notice that this fails.

Tiling in other directions still works.

**Screenrecording**
![Issue1](https://github.com/user-attachments/assets/686c607a-6e21-4a4a-922c-9dcdafaf6786)

The recording first shows that retiling after untiling works correctly toward distant screen borders, but then demonstrates the failure when tiling toward a very close screen border.

### Second Issue 

Occurs when positioning the window so it overlaps two tiles, while keeping the center in one tile (e.g., the left). Tiling toward the other tile (e.g., right) does not work as expected.

**Steps to Reproduce**

1. Position the window with the mouse so it overlaps two tiles, but keep its center within one (e.g., the left tile).
2.  Try tiling the window to the opposite tile using hotkeys.
3.  Notice that the window tiles to the tile where its center is located instead.

After using hotkeys to untile, tiling works as expected.

**Screenrecording**
![Issue2](https://github.com/user-attachments/assets/d2b7386b-2040-4e5c-b3ec-353123c117ba)

(I forgot to enable the mouse pointer display in the screen recording.)

**Comment by SuiziM** [comment]
Sorry, for the spam. Not familiar with Github.

**Comment by domferr** [comment]
Hey @SuiziM thank you for the feedback. The second issue is how Tiling Shell works. The algorithm in that particular occasion chooses the nearest tile to the center. Did you expect another behavior, such as the nearest tile in the direction of the hotkey? The issue one seems a little bit particular and I'm able to reproduce the problem. I'm working on a fix :smile:

**Comment by SuiziM** [comment]
Sorry, for taking a while to answer. 

Regarding the "second issue": When I use the 'Move tile to right' hotkey in that case, the window moves to the left, which is odd to me.

This  becomes even more noticeable in the following screencast: if I shift the window just a few millimeters, the same hotkey produces entirely different behavior.

![MoveToRight](https://github.com/user-attachments/assets/a3cf73fd-0d04-484e-b16d-bd899646fc32)

I don't think anyone would expect the window to tile to the left in this case.

**Possible Improvement: Reference Point Based on Direction**
Playing around with more "advanced" tiling layouts,  trying out the tiling hotkeys and thinking it through, I feel like the reference point should depend on the direction i.e 

- When moving to the right, the reference point should be the right-center.
- When moving to the top, the reference point should be the top-center.
- etc.

Maybe with a slight offset towards the center, might involve some trial and error to see what's really intuitive. 
[Reference for points](https://lh5.googleusercontent.com/proxy/15GHYBsS4ks-IpTiXDlyOl88zqybQM29V32G-CHRal5z5_Gi_jt8cXiXv3A1ynkmFExp3BdtnUeS2_pPZbHuf5uOpS-ozFTdMISzhwp-NmPTgi2MhZZolakHAKD5bgftFuU2nl1pQgImoIa3)


**Inconsistent Behavior Based on "Positioning Method"**
Even if I'm okay with this behavior, it's still a bit weird that the hotkey behaves differently depending on how the window is positioned:

 - If I position the window with the mouse, the hotkey acts differently than when the window reaches the same position through the untile hotkey (as seen in the second screencast in my previous comment).

The behaviour of the "Span window to X / Above /Below" hotkey also gets changed by the "Untile"-hotkey compared to moving it there by mouse.

**Comment by domferr** [comment]
Hey thank you for sharing this! I agree with you: Tiling Shell's keybindings behave differently when a window is untiled and this is counter intuitive. IDK why I made this :laughing: 

I removed such difference, check it out and let me know how it is now! Thank you

[tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17747251/tilingshell%40ferrarodomenico.com.zip)

**Comment by domferr** [comment]
Now available in Tiling Shell v15.0
