### ISSUE TITLE
Vim-like keyboard shortcuts for navigation between windows (i3 killer feature)

### ISSUE THREAD

**Issue by Tyrn** [domferr/tilingshell#187]
Window navigation keyboard shortcuts: left hand on a key to the left of Space (a key combination, if absolutely necessary), a right hand finger presses H J K L.

If such bindings already exist, they should be documented. Or collected into a nice, visible, convenient table, if they are documented already.

**Comment by thyttan** [comment]
I map it to ALT+SUPER+h/j/k/l in the extension settings.

**Comment by Tyrn** [comment]
I'm sorry. Where are they? I suppose, somewhere inside `~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com`, between `extension.js` and `prefs.js`. Still, I don't get it. Could you explain a bit more?

**Comment by thyttan** [comment]
I use this app: https://apps.gnome.org/Extensions/

**Comment by domferr** [comment]
You can access Tiling Shell's preferences from the app @thyttan is using or via terminal by running `gnome-extensions prefs tilingshell@ferrarodomenico.com`. Over there you can bind the keybindings you prefer and customise other settings too! Let us know how it goes! Enjoy Tiling Shell

**Comment by domferr** [comment]
Closing for no info
