### ISSUE TITLE
Use version_name instead of version number

### ISSUE THREAD

**Issue by in4matix** [domferr/tilingshell#19]
Finally decided to install it from GSE. Not sure if intentional, but version is:

![Screenshot from 2024-06-13 17-56-01](https://github.com/domferr/tilingshell/assets/62904593/b29c3949-d21f-4358-ad5f-11b4c76d2994)

**Comment by domferr** [comment]
Thank you for opening this issue and for testing the GSE version too!

Before uploading on GSE I was manually increasing the version number after each update. Then, after uploading on GSE, I discovered that they start back from version number 1. Moreover, the extension for GNOME shell 45 and 46 also has a different version number compared to the one for GNOME shell 44 or lower.

I will keep this issue open to remember that in future updates we need to stop using version numbers and use the **version_name** instead.

**Comment by domferr** [comment]
I forgot to say that the extension was reviewed by GSE admins and some changes were made to adhere to some best practices. So the first time I uploaded in GSE we started from version 1, then we ended up reaching version 5 because of their suggested changes.

From a practical point of view, the one on GSE is identical to the one you were using before.

**Comment by domferr** [comment]
:heavy_check_mark: Done in version 8.0!
New version will be available on GSE soon and can be already downloaded from GitHub releases.

**Comment by in4matix** [comment]
Thank you Mr. Fast And Furious! ;-) I love the new changes that you implemented! I've grabbed it from releases until it's on GSE. 
BTW. With working with the manual installations for a while now, I simply disable, then delete the old version, then reinstall and enable the new version. The export and import function is going to be super handy for sharing layouts with different machines and friends.

**Comment by domferr** [comment]
Thank you @in4matix!

P.S: it seems reviewers on GSE are super fast too, the new update got just accepted!

> With working with the manual installations for a while now, I simply disable, then delete the old version, then reinstall and enable the new version.

That's definetly the best way to do it!
