### ISSUE TITLE
Cannot move window to Tile on other Monitor with Keyboard Shortcuts

### ISSUE THREAD

**Issue by JulsRX** [domferr/tilingshell#197]
**Describe the bug**
Cannot move window to tile on other monitor with keyboard shortcuts

**To Reproduce**
- Set Keybindings for "Move window to right tile" and  "Move window to left tile".
- Focus a window
- use keyboard to move window towards a tile on another monitor on left or right
- Window will get "stuck" at the edge but will not move to a tile on the other monitor

**Information (please complete the following):**
 - Tiling Shell version: 15
 - GNOME version: 46

**Additional context**
Moving windows with keys worked flawlessly in at least Tiling Shell version 14. Did not change the settings when upgrading to version 15.
Tested different windows, restarted and reinstalled Tiling Shell and changed other settings (i. a. auto tiling). Restarted the system.

**Comment by domferr** [comment]
Hey thank you for sharing this bug and making to many tests! Unfortunately, as you noticed, this bug was introduced by the latest version. I'm working on a bugfix which will be available soon! :soon: 
I'll keep you updated :smile:

**Comment by domferr** [comment]
Hey, quick update. Meanwhile the bugfix gets published, I'll leave the update to you in advance!

- For GNOME Shell 42, 43 or 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17922215/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- For GNOME Shell 45, 46 or 47: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17922218/tilingshell%40ferrarodomenico.com.zip)

**Comment by domferr** [comment]
:heavy_check_mark: Available in version 15.1! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
