### ISSUE TITLE
Add support for windows being dragged by holding down super key

### ISSUE THREAD

**Issue by underdoeg** [domferr/tilingshell#20]
Currently tiling assistance only works when dragging windows from the title bar and not when holding the super key.

Awesome extension BTW

**Comment by domferr** [comment]
Hi, thank you for opening this issue!
Are you referring to `SUPER + ARROW KEY`?. For example, GNOME default's behavior, when you press `SUPER + LEFT ARROW` tiles the window to the left (following its default 2 columns)

> Awesome extension BTW

Thank you, I'm glad you are enjoying it! Feel free to open a issue for sharing any idea or bug you may have :)

**Comment by Mordynak** [comment]
> Hi, thank you for opening this issue! Are you referring to `SUPER + ARROW KEY`? For example, GNOME default's behavior, when you press `SUPER + LEFT ARROW` tiles the window to the left (following its default 2 columns)
> 

OP is talking about Gnomes default behaviour of being able to drag a window with the cursor in any location within the window whilst holding the super key.

**Comment by underdoeg** [comment]
> > Hi, thank you for opening this issue! Are you referring to `SUPER + ARROW KEY`? For example, GNOME default's behavior, when you press `SUPER + LEFT ARROW` tiles the window to the left (following its default 2 columns)
> 
> OP is talking about Gnomes default behaviour of being able to drag a window with the cursor in any location within the window whilst holding the super key.

yes.  that is what i meant.  thx

**Comment by domferr** [comment]
Well, that's great since this feature is already under testing and it will be available in the next update! :smile: 
I'll comment here when it will be published on GSE

**Comment by domferr** [comment]
:heavy_check_mark: Done in version 8.0!
New version will be available on GSE soon and can be already downloaded from GitHub releases.

**Comment by underdoeg** [comment]
i have already ulgraded to v8. but it looks like it is not working for me. i should be able to first drag the window with suler key and then see the tiling options with ctrl key?

**Comment by domferr** [comment]
Hi @underdoeg, you can go to the extension preferences and choose `SUPER` as your preferred activation key for the tiling system. Then, you will be able activate the tiling options while moving a window and pressing `SUPER` key.

![image](https://github.com/domferr/tilingshell/assets/14203981/43a9d821-510e-4e77-b5ec-a9bc748a890b)

**Comment by underdoeg** [comment]
Ah I think we are talking about different things. 

I tried to record it in a video. At first I drag the window "the normal way" by klicking on the header and dragging.
The second time, I click anywhere in the window while holding super. That way I can also drag the window but the tiling extension does not appear.

https://github.com/domferr/tilingshell/assets/243820/6b8ab0ca-5098-4291-a1c0-a4414acb9624
