### ISSUE TITLE
Snap assistant threshold only works up to 200 or so (with max input value of 512)

### ISSUE THREAD

**Issue by joonas-ris** [domferr/tilingshell#205]
~~Setting a value through the text input only works to around 200 or so. Plus button works to the full allowed 512.~~

e. on a second look, looks like 200 (or so) is the true max and anything above isn't an actual working value.

Resolution 3840x1600, scaling 100%, Wayland, Gnome 47

**Comment by domferr** [comment]
Hey, thank you for sharing this. Wow, that's strange! I can reproduce the issue, I was not aware of it ahahha The fix will be available with the next upcoming release (v15.1)

**Comment by joonas-ris** [comment]
No problem! I was afraid that I had something uniquely wrong or that my issue wasn't reproducible or fixable. Glad you can take a look at it!

**Comment by domferr** [comment]
:heavy_check_mark: Available in version 15.1! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
