### ISSUE TITLE
Exit tiling screen with escape or clicking elsewhere

### ISSUE THREAD

**Issue by tflori** [domferr/tilingshell#207]
**Describe the bug**
Honestly I'm not sure if it is a bug or a feature. When you snap a window into a tile and a tile next to it has no window and there are windows that could fill the tile you get the "tiling screen" where you can chose for one of the tiles which app should be moved to this tile. Now I would naturally press escape because something happened that I didn't initialize and it is kind of blocking me from continuing. But even clicking on the tile outside of any window does not do anything. The only way to close it without choosing a window is by pressing super (win) to open the activity view.

**To Reproduce**
1. Open two apps
2. Tile one to a tile 

**Screenshots**
![image](https://github.com/user-attachments/assets/2a35a31f-3a97-4c25-ab43-8e7579104967)

**Information (please complete the following):**
 - Tiling Shell version: jesse/focus-next-prev
 - GNOME version: 46.0

Please keep in mind that adding a configuration for a key will most like cause issues if you want to bind escape (the dialog closes with escape).

**Comment by domferr** [comment]
Hey thank you for sharing this! That is a new feature coming soon in Tiling Shell. It will be possible to enable and disable it from the preferences. I see you are using your git branch and maybe you pulled the latest changes of branch v15.0 and you are seeing that popup! The feature is not yet complete and what is missing is the ability to close that popup by pressing ESC. The only way to close it is to press outside a tile, but it seems it's not working to you :|

You can have a look at issue #62 to know more about this feature! Meanwhile, I'm gonna push to branch v15.0 some code to allow pressing ESC key to close the popup. I'm back to you in minutes

**Comment by domferr** [comment]
Hey @tflori I just pushed a commit to allow pressing ESC to close the tiling popup. Let me know if that works for you! Hope to implement soon the ability to enable/disable this feature from the preferences

**Comment by tflori** [comment]
works as expected. yes, I'm on the branch from jesse with the fix for the focus keybindings. it was rebased on 15.1 

whats the plan for the release? will it include #195 ? 

I guess we can close that then as it is no bug of the stable version...

**Comment by domferr** [comment]
> whats the plan for the release? will it include https://github.com/domferr/tilingshell/pull/195 ?

Yes, it will! But It won't include the tiling popup.

> I guess we can close that then as it is no bug of the stable version...

I agree
