### ISSUE TITLE
Tray menu entry for more settings

### ISSUE THREAD

**Issue by bmaupin** [domferr/tilingshell#208]
First of all, amazing extension, thank you so much for it!

The only thing I don't like is that in order to change any settings not related to layout you have to go into Gnome Extension Manager. I would love it if instead there would be an option in the tray menu to go there directly, "More Settings" or something like that.

I would be happy to submit a pull request if this is something that would be accepted.

For comparison, Tiling Assistant has a _Preferences_ option:
![tiling-assistant](https://github.com/user-attachments/assets/6f2120b0-fad2-4917-bf09-a52119bbcb5c)

and gSnap has _Settings_:
![gsnap](https://github.com/user-attachments/assets/7f1eb4ea-c10f-4e9a-9c54-a536626941cf)

Thanks!

**Comment by domferr** [comment]
Hey thank you for this suggestion. You read my mind: I'm currently working on this! :star2:
It'll be available with the next upcoming release (v15.1)

**Comment by domferr** [comment]
:heavy_check_mark: Available in version 15.1! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
