### ISSUE TITLE
Question: how does the indicator menu icon change color to match the current theme?

### ISSUE THREAD

**Issue by jessedhillon** [domferr/tilingshell#214]
Sorry, this is not a feature request but just a question:

I've noticed that the indicator menu icon's SVG has `fill="white"`. However, despite this, the color of the icon will change to be dark, light, or whatever it needs to be to match the currently active theme. Can you explain how that is achieved? Thank you

**Comment by jessedhillon** [comment]
Thanks Dom -- does the extension change the color programmatically by listening for a style change or something? Or does GNOME automatically handle this?

**Comment by domferr** [comment]
Is GNOME that does it behind the scenes!
