### ISSUE TITLE
Portrait orientation support

### ISSUE THREAD

**Issue by na1811kodehode** [domferr/tilingshell#219]
Hello, I would love the addition of monitor portrait orientation support. A lot of us have a 2nd monitor oriented vertically and I think a feature like that would be huge, currently I am unfortunately forced to use gSnap to support tiling on my 2nd monitor and if such a thing would get added to this extension then I wouldn't need to use any other extension.

Thank you for all the hard work you do <3

**Comment by domferr** [comment]
Hey thank you for your suggestion! I'm curious to know what is not working. Can you show some images or videos? Because tiling shell already supports vertical monitors! Thank you! 😊

**Comment by domferr** [comment]
Currently is only possible to create a layout on the primary monitor. In the future I'll add the ability to select the monitor on which the editor appears. If you wish to already create a layout on the portrait monitor you can set that as primary or you can disconnect the other monitors you have. Thank you

**Comment by na1811kodehode** [comment]
> Currently is only possible to create a layout on the primary monitor. In the future I'll add the ability to select the monitor on which the editor appears. If you wish to already create a layout on the portrait monitor you can set that as primary or you can disconnect the other monitors you have. Thank you

Thanks for the workaround, I will definitely do that! :)

**Comment by Waldorf3** [comment]
Sorry, I don't mean to reopen or hijack a closed issue, but otoh I don't think it makes sense to open a second post with an extension of the same issue. 

Similar to the OP I have a screen setup with a large main horizontal main monitor and a smaller vertical side monitor.  It only ever make sense for me to split the vertical screen horizontally in the middle, whereas the main screen I split in various ways, pretty much the standard setup.  

I was wondering if it was possible to have a simpler layout set for the side monitor?  

Clicking on the tiling indicator shows the layout options for each screen. They are both identical by default, but it kinda suggest it could be possible to have different layout-sets for each monitor?   Am I missing something, or is it perhaps something planned?

**Comment by domferr** [comment]
Hey @Waldorf3 thank you for sharing this! I hope to give you a hand

The layout editor (as of today) let's you edit a layout on one monitor only. Unfortunately, you will need to guess. Probably cutting the screen in a half is enough. Then Tiling Shell will let you use that layout on any monitor. You can have different layouts for each monitor. Go to the indicator icon and you will access a menu showing you separated layout selection for each monitor. Feel free to ask any questions you might have!

<p align="center">
<img src="https://github.com/domferr/tilingshell/assets/14203981/d0261742-eb7c-4fbf-ab7b-da638d31378c" />
</p>

**Comment by Waldorf3** [comment]
Thanks. Yes I now you can select different layouts for each monitor, but both monitors have the same selection. What I was after was having just one layout for the vertical display. It would make it easier to move windows around, As it is I would have to first find the line of layouts, then pick the upper or lower half of the option split in the middle. 

Anyway, as I said, would just be a nice-to-have. :)
