### ISSUE TITLE
`Move Window To Next Tile` across monitors

### ISSUE THREAD

**Issue by mrchantey** [domferr/tilingshell#222]
On my setup `Super+Left/Right` works to the edge of Monitor A but it doesn't allow me to push the window onto the first tile of Monitor B. This would be a huge win for my productivity.

btw thanks for the awesome extension!

[Edit]
Ok this morning it just started being able to do that, maybe there is something that was preventing it previously? I know totally unreproducable but ill report here if I find out why.

**Comment by domferr** [comment]
Hey thank you for sharing this! Latest update of Tiling Shell fixed the problem that you had. This might be the reason why that bug is not occurring to you anymore!
