### ISSUE TITLE
[Feature Request] ESC key for leaving layout editing mode

### ISSUE THREAD

**Issue by Ghorin46** [domferr/tilingshell#24]
Hello
When you are editing a layout, you have to go into the extension menu on the top panel.That's fine for me when I want to save the layout. But if don't want to save, only quit the layout editor, then in my opinion it would be better to have a quick key shortcut. And I propose the ESCape key (if it doesn't interfere with Gnome Shell).

**Comment by domferr** [comment]
Hi, thank you for sharing this idea! It may be a good option to allow pressing ESC to close the layout editor

**Comment by dhitchcock** [comment]
Or at least mention in the helper popup how to get save/cancel, this bug ticket was where I discovered how to get out of edit mode :laughing:

**Comment by domferr** [comment]
> Or at least mention in the helper popup how to save/cancel, this bug ticket was where I discovered how to get out of edit mode 😆

Hey @dhitchcock, following your suggestion I updated the helper popup, thank you! It will be available soon in the next update (v9.0)

**Comment by domferr** [comment]
Closing this, since GNOME shell doesn't allow us to do it in a reliable way.
