### ISSUE TITLE
Add option to change the spacing between the windows

### ISSUE THREAD

**Issue by sekurilabs** [domferr/tilingshell#28]
It would be great to have the option to edit the space between the windows. Some people use tilled windows with no space between them (like me for example), some may want smaller of bigger spacing.

**Comment by domferr** [comment]
Hey @sekurilabs thank you for your suggestion. It is already possible to do so! In the extension preferences you can set the gaps between the windows and the gaps with the screen. If you like no space between windows, you can set the inner gaps to zero!

![image](https://github.com/domferr/tilingshell/assets/14203981/a8d16b8a-5cf7-4158-8a6a-d4856a4d689b)

**Comment by sekurilabs** [comment]
I have missed that! Thank you! Goodbye tilling assistant, welcome tilling shell :)
