### ISSUE TITLE
Mention extensions.gnome.org in readme

### ISSUE THREAD

**Issue by vinicentus** [domferr/tilingshell#30]
Currently the Readme states that the extension isn't available on extensions.gnome.org, howver it is actually available now (woohoo 🎊).

This should probably be updated in the readme. :D

EDIT: I see that there is a link to it in the readme, but in the instalaltion section it still says it isn't available.

**Comment by domferr** [comment]
Hi @vinicentus, thank you 🎊! I forgot to update that ehehehe
