### ISSUE TITLE
Snap assistant not working/showing properly with Firefox

### ISSUE THREAD

**Issue by sebastiaanfranken** [domferr/tilingshell#32]
I am using this extension on Fedora 40. It works really well, except for Firefox. The snap assistant does show, but it's behind the main Firefox window, so it's really hard to get Firefox to "snap" into place that way. Moving it and pressing control works, but sometimes I want to not use the default selected layout.

This is hard to explain. If I need to screenshot this (if possible), let me know.

**Comment by sekurilabs** [comment]
Moving snap assistant to foreground would be helpful if possible. It's always behind the window so it is a bit hard for some applications to get it where you want. I don't know if it's possible to move the assistant "in front" of the application for easier snapping.

**Comment by domferr** [comment]
Hi, thank you for sharing this issue! I can confirm that for some apps it's in background while it should be in foreground. Hope to fix this soon in the next update.
I leave attached a bugfix, can you confirm it is solved?

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15883508/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15883512/tilingshell%40ferrarodomenico.com.zip)

**Comment by sebastiaanfranken** [comment]
> Moving snap assistant to foreground would be helpful if possible. It's always behind the window so it is a bit hard for some applications to get it where you want. I don't know if it's possible to move the assistant "in front" of the application for easier snapping. Update: for some apps it's in foreground for some in background. For example terminal, firefox background, teams foreground.

For me it's only "behind" with Firefox. The rest of the applications I use it's nice in front, as it should be (I assume?)

**Comment by sebastiaanfranken** [comment]
> Hi, thank you for sharing this issue! I can confirm that for some apps it's in background while it should be in foreground. Hope to fix this soon in the next update. I leave attached a bugfix, can you confirm it is solved?
> 
>     * GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15883508/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
> 
>     * GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15883512/tilingshell%40ferrarodomenico.com.zip)

Can confirm that works with Fedora 40 with GNOME 46 and Firefox.

**Comment by domferr** [comment]
> For me it's only "behind" with Firefox. The rest of the applications I use it's nice in front, as it should be (I assume?)

Yes, it should be in front of any window.

> Can confirm that works with Fedora 40 with GNOME 46 and Firefox.

Great! Thank you!

**Comment by sebastiaanfranken** [comment]
Since your posted build fixes it, want me to close the issue, or do you want to do that in the next release?

**Comment by domferr** [comment]
> Since your posted build fixes it, want me to close the issue, or do you want to do that in the next release?

Let's keep it open until the new version lands on GSE, thank you!

**Comment by domferr** [comment]
Hey @sekurilabs thanks a million! :heart:

**Comment by domferr** [comment]
:heavy_check_mark: Completed in version 9.0! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
