### ISSUE TITLE
[Feature request] Allow snapping windows to corners and edges by moving them there

### ISSUE THREAD

**Issue by Moudoux** [domferr/tilingshell#35]
**Describe the feature you'd like**
Currently you have to hold CTRL (or what the user has set it to) to enable the tiling system.
It would be great if there was a setting to enable snapping windows to corners by moving them to the corners (Similar to how it works in Windows 11), without holding any key on the keyboard. Specifically corner snapping with the window taking up 1/4 of the screen, since Gnome already supports snapping windows to half the screen by moving them to the side.

**Additional context**
There already exists an extension that does this (WinTile), however, it is kind of buggy and doesn't really work as it should. It would make sense to add this feature to this extension since it already does window snapping.

I'd also just like to say that this is by far the best tiling extension for Gnome

**Comment by domferr** [comment]
Hey thank you for your suggestion! I was thinking about it too, it would be very nice!
At first I may implement it with fixed quarter tiles, so moving the window to the corners it can be snapped to that 1/4 of the screen. Later, when that feature will be reliable enough, I would like to allow using the layout editor to edit that too! Basically giving the freedom to have any behavior you may prefer when moving a windows to the side of the screen or to the corners.

> I'd also just like to say that this is by far the best tiling extension for Gnome

Thank you! I'm glad you are enjoying it!

**Comment by kleinHeiti** [comment]
I would like to give you a little hint: Please don't just add a 1/4 snap. Please also include a 1/1 (i.e. fill the full screen / maximize the window). 

The layout selection becomes visible when the mouse pointer moves to the centre of the top edge, but does not take up all the space there. 

So if the mouse moves past the layout selector to the edge, this could maximise the window. 

This is also how it works in Win 11 and would adjust the behaviour accordingly.

**Comment by domferr** [comment]
> I would like to give you a little hint: Please don't just add a 1/4 snap. Please also include a 1/1 (i.e. fill the full screen / maximize the window). 
> 
> 
> 
> The layout selection becomes visible when the mouse pointer moves to the centre of the top edge, but does not take up all the space there. 
> 
> 
> 
> So if the mouse moves past the layout selector to the edge, this could maximise the window. 
> 
> 
> 
> This is also how it works in Win 11 and would adjust the behaviour accordingly.

Hey, I totally agree with you! I think that how Windows 11 handles edge tiling has great UX and it is actually useful.

**Comment by kleinHeiti** [comment]
Oh, I got exactly the described behaviour when I activated Tilling Assistant in addition to Tilling Shell (I did it by mistake). 

Works well together.

**Comment by kleinHeiti** [comment]
[Bildschirmaufzeichnung vom 2024-06-22 10-27-16_1.webm](https://github.com/domferr/tilingshell/assets/54942072/fbcb7fed-c190-45d4-b94d-b7bc91cb109a)

**Comment by domferr** [comment]
I've been working on this lately. If you want to try it in advance, I leave here the new version (v10)! It's still under development, so if you try it please share any feedback or bug!

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15938184/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15938186/tilingshell%40ferrarodomenico.com.zip)


[Screencast from 2024-06-22 22-12-22.webm](https://github.com/domferr/tilingshell/assets/14203981/6e5a2ba9-cd38-44bb-b791-51e41e07f7a0)
