### ISSUE TITLE
[Feature Request] Extension won't activate when moving windows using super.

### ISSUE THREAD

**Issue by bvgross** [domferr/tilingshell#37]
**Describe the bug**
I tend to use super + click to move and resize windows because some of my applications don't have a titlebar (kitty for example), so it's impossible to tile them with the extension. I don't know if this is a new feature to be implemented or an bug/issue.

**To Reproduce**
1. Hold super
2. Click and hold anywhere window you want to move and move it
3. Tiling assistant won't appear, and activation key won't work

**Information (please complete the following):**
 - Tiling Shell version: 7
 - GNOME version: 46

**Comment by domferr** [comment]
Hi, thank you for your suggestion! This is something I was working on lately, 🔜 It will be available soon in the next update (v9.0)!

**Comment by Neon-44** [comment]
Don't know if this should be an extra Issue, but:

if I "snap" a Window, it's size will get adjusted (naturally)
if I then move it by dragging it at the taskbar, it returns to its original size (really cool)
if I move it by dragging it using the Meta Key, it doesn't return to its original size

Should I make a new Issue? Or does this belong here? Or maybe it's a wontfix?

amazing extension btw, thanks for sharing it :)

**Comment by domferr** [comment]
> if I move it by dragging it using the Meta Key, it doesn't return to its original size

Hmmmm, that doesn't seem to be right. Is Meta key the Super key or they are two different buttons?

> amazing extension btw, thanks for sharing it :)

Thank you! I'm happy you are enjoying it!

**Comment by Neon-44** [comment]
I just assumed they were the same Button, but it seems I was wrong. I of course meant the Super Key. The one with a windows logo.

**Comment by domferr** [comment]
Uh ok! So yeah, next version (v9.0) will have that feature too. The good news is that it will be published soon, I'm waiting for the approval :partying_face:

**Comment by domferr** [comment]
:heavy_check_mark: Completed in version 9.0! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>

**Comment by Neon-44** [comment]
I'm really really sorry I to be that guy, but:

Could you possibly add support for resizing with super+right_mouse_button?

If I resize normally, it will also resize the adjacent window. But it won't if I resize with super+rmb.

I feel really really bad to annoy you again, so please be brutally honest if it's too much effort to do! :)
I am already really really glad you share this extension with us as it is! :)

**Comment by domferr** [comment]
Hey @Neon-44 don't be sorry! It's a pleasure!
I'm not used to that hotkey, so I'm trying to understand. However, if I press `SUPER` + `RIGHT CLICK` I get this:

![image](https://github.com/domferr/tilingshell/assets/14203981/eed2a795-e564-4dc9-ab5f-18e66ab2dead)

What am I doing wrong?

**Comment by Neon-44** [comment]
oh, right, sorry, I sometimes forget I customize my Gnome.
It's so natural to me, I just assume it's the Default, apologize for that.

It's a Dconf Setting I think?
org/gnome/desktop/wm/preferences/resize-with-right-button?

I understand if you say that this is too much of an effort for what is probably a minority of gnome users. I really don't want to increase your workload, I really am already super glad for what you gave us 🤗
