### ISSUE TITLE
[New Feature] Blur!

### ISSUE THREAD

**Issue by domferr** [domferr/tilingshell#38]
Well...it would be nice to have blurred tile previews and snap assistant! Here it is!

![image 2(1)](https://github.com/domferr/tilingshell/assets/14203981/35bff2a1-2b9b-4840-b72a-aee880d30f52)

I'm seeking for feedback, please share yours! Should it be the default? Do you believe it is better white blurred ( :arrow_left: left image) or it should follow the shell theme color ( :arrow_right:  right image)?

![blur](https://github.com/domferr/tilingshell/assets/14203981/c917c082-1fd9-4366-85b2-1daaed5890c9)

# Video
[Screencast from 2024-06-20 22-51-53.webm](https://github.com/domferr/tilingshell/assets/14203981/1ac73716-922a-4747-babe-e2d61d8d0fd6)
> The snap assistant is blurred in the previous images. In this video the snap assistant is not blurred.

# Issues
- [GNOME shell bug #2857](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2857) is a big problem. I have a workaround I'm testing.

**Comment by in4matix** [comment]
@domferr , I'm not a huge fan of blur as it serves no practical purpose. I am however a huge fan of transparency / opacity as it allows one to see important information behind the focused window. For example, I often type commands from a website in my terminal, and because my terminal is semi-transparent, I can see the commands on the website behind my terminal.

**Comment by kleinHeiti** [comment]
First of all, I really like the blur effect in the snap assistant. That could be the default setting for me

I could imagine that it works better for the individual if the colour is based on the shell theme. 

It probably looks more consistent then.

**Comment by ebits21** [comment]
Love the blur and makes sense to follow the shell theme (and/or allow a light/dark switch in the settings).

**Comment by domferr** [comment]
Thank you guys for your feedback! :heart: 
This feature is coming soon :soon:

**Comment by EfogDev** [comment]
Beautiful
