### ISSUE TITLE
[Testing] GNOME 43 compatibility

### ISSUE THREAD

**Issue by domferr** [domferr/tilingshell#4]

**Comment by in4matix** [comment]
Playing around with Debian Bookworm, so I throught I'd try MWM. Issue discovered:

[Screencast from 2024-06-14 23-14-13.webm](https://github.com/domferr/tilingshell/assets/62904593/18352666-154d-4fc8-bec3-cb85e0d9bdd3)

**Comment by domferr** [comment]
Hey @in4matix  thank you for your comment! This bug appears to me since day one, but only in some very weird and specific situations. After some research it seems that the problem lies behind some strange gnome-shell behavior that I'm still trying to understand. It is rare but I encountered this bug at least once while testing for GNOME 44 and 46 but in virtual machines only.

This problem arises only once to me: can you confirm that if you open new windows they are not affected by that issue?
I was thinking about a bug fix, however since it is difficult to reproduce I was not able to understand this issue properly. Any info you can provide would be very useful!

**Comment by in4matix** [comment]
Hey @domferr 

>  It is rare but I encountered this bug at least once while testing for GNOME 44 and 46 but in virtual machines only.

Ah, okay, Debian Bookworm is running in a VM, so chances are good that the issue does not effect physical Debian systems.

Other than this, TS is working well on Debian Bookworm VM.

**Comment by domferr** [comment]
Hi, I leave attached a bugfix, can you confirm it is solved?

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15883508/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15883512/tilingshell%40ferrarodomenico.com.zip)

**Comment by in4matix** [comment]
Hi, I can confirm that it is solved.

[Screencast from 2024-06-18 14-36-16.webm](https://github.com/domferr/tilingshell/assets/62904593/dda3d1d5-1998-4248-85db-93cdf41cfc31)

**Comment by domferr** [comment]
> Hi, I can confirm that it is solved.

Thank you @in4matix !
