### ISSUE TITLE
Edit Layouts button doesn't work

### ISSUE THREAD

**Issue by twkonefal** [domferr/tilingshell#41]
**Describe the bug**
When opening the Tiling Shell gear icon to configure Appearance, Behaviour, and Layouts, the Edit layouts button doesn't work. Clicking it has no effect.

 - Tiling Shell version: v9.0
 - GNOME version: GNOME Shell 46.2

**Comment by domferr** [comment]
Thank you for reporting this bug! I published a bug fix and it is under review.

Meanwhile, if you want the bug fix, you can download the latest release ([v9.1](https://github.com/domferr/tilingshell/releases/tag/9.1.0)).
