### ISSUE TITLE
Super+←↑↓→ are suddenly rediefined

### ISSUE THREAD

**Issue by Lapizistik** [domferr/tilingshell#43]
**Describe the bug**
I have `<Super>←`, `<Super>→`, `<Super>↑`, `<Super>↓` (left, right, up, down) mapped to switch workspaces (matrix layout).
With the new version of tilingshell the keys are redefined and I have no way to get them back
(I would be fine with being able to redefine the tilingshell keys through dconf-editor or what, or just switch off the remapping at all, but at a first glance I don't see how to easily do this).

**To Reproduce**
1. Bind `<Super>←` to anything in gnome shell
2. Enable tilingshell
3. Try to use `<Super>←`

**Information (please complete the following):**
 - Tiling Shell version: [e.g. v9.1]
 - GNOME version: 43.9 (on Debian bookworm)

**Additional context**
I had a glimpse on the code and [this comment](https://github.com/domferr/tilingshell/blob/5ba65f9d027033d328af4dba085a65cb76ad3f6e/src/keybindings.ts#L22) suggests this is currently hardcoded and I don't see a way to disable this.

**Comment by domferr** [comment]
Hi, thank you for sharing this! It's definitely bad that there isn't a way to customize Tiling Shell's keybindings or to at least disable/enable them!

I will prioritise this in the next update (next week). 

Meanwhile, if you prefer you can install the previous version (v8.0), which doesn't redefine the keybindings

**Comment by Lapizistik** [comment]
Thanks a lot!
And thank you for your work, I really like your extension!

**Comment by ilyachch** [comment]
I think it will be also very useful to have an ability to disable hotkeys

**Comment by thyttan** [comment]
> Hi, thank you for sharing this! It's definitely bad that there isn't a way to customize Tiling Shell's keybindings or to at least disable/enable them!
> 
> I will prioritise this in the next update (next week).

Thanks for prioritizing this! I was about to open a feature request for letting the user choose their own keybindings (Personally my goal is to change from `SUPER+[arrow key]` to `SUPER+ALT+h/j/k/l` for moving windows around).

**Comment by domferr** [comment]
Here we are! :partying_face: 

![image](https://github.com/domferr/tilingshell/assets/14203981/f0dcbf7b-d1d3-4da7-b9fe-a37bec10ec25)

In this update you can enable/disable the keybindings or change them.
This is coming soon this week with version 10.0. If you want to try it in advance, I leave here the files. Enjoy!

- GNOME 42, 43 or 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15984485/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 or 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15984488/tilingshell%40ferrarodomenico.com.zip)

**Comment by thyttan** [comment]
One of the many things I like about Tiling Shell is the fact that it works so nicely with the [Gesture Improvements](https://github.com/harshadgavali/gnome-gesture-improvements) extension.

But when I change the `Super`+`←↑↓→` keybindings to `SUPER`+`ALT`+`h/j/k/l` in Tiling Shell **Gesture Improvements** breaks.

To fix this I applied this change to **Gesture Improvements**:
```diff
diff --git a/gestureImprovements@gestures/src/snapWindow.js b/gestureImprovements@gestures/src/snapWindow.js
index 59acc9d..07ee96c 100644
--- a/gestureImprovements@gestures/src/snapWindow.js
+++ b/gestureImprovements@gestures/src/snapWindow.js
@@ -117,7 +117,7 @@ const TilePreview = registerClass(class TilePreview extends St.Widget {
 				// snap-left,normal,snap-right
 				else {
 					if (state !== GestureTileState.NORMAL) {
-						const keys = [Clutter.KEY_Super_L, (state === GestureTileState.LEFT_TILE ? Clutter.KEY_Left : Clutter.KEY_Right)];
+						const keys = [Clutter.KEY_Alt_L, Clutter.KEY_Super_L, (state === GestureTileState.LEFT_TILE ? Clutter.KEY_h : Clutter.KEY_l)];
 						this._virtualDevice.sendKeys(keys);
 					}
 				}
```
