### ISSUE TITLE
Tilling does not respect the edge of the monitor in a multi-monitor setup.

### ISSUE THREAD

**Issue by kleinHeiti** [domferr/tilingshell#44]
Before the update to version 9.1, a window that was placed on the right edge of the first (left) monitor via the layout wizard was correctly placed on the edge of the monitor.

With today's update, the tilling takes place beyond the edge of the monitor (see screenshot).

![Bildschirmfoto vom 2024-06-23 10-46-02](https://github.com/domferr/tilingshell/assets/54942072/cbd87672-03a4-4ae7-bed6-a827259bc92e)

**Comment by kleinHeiti** [comment]
I'm sorry. After disable and reenable the extenstion again, the issue is gone. Sorry to take your time.

**Comment by domferr** [comment]
Hey, don't worry and thank you for reporting that issue! Feel free to reopen it at any time if you find this bug again!
