### ISSUE TITLE
Ability to add padding around windows

### ISSUE THREAD

**Issue by GilesMunn** [domferr/tilingshell#46]
It would be nice to have some user-configurable option (perhaps under Edit Layouts) of the padding - in pixels - between the windows and each other, and between the windows and the bezel of the monitor. 

Thanks for a great extension!

**Comment by domferr** [comment]
Hey, thank you for sharing your suggestion! I'm happy to say that Tiling Shell already comes with that feature 🥳 
That settings are named "Inner Gaps" and "Outer Gaps". Check them out, you can find them in the extension preferences

**Comment by GilesMunn** [comment]
So it does, my mistake - thank you!
