### ISSUE TITLE
[Feature Request] Associate tiling to workspaces

### ISSUE THREAD

**Issue by PHHENS** [domferr/tilingshell#47]
Dear Developer,
Greatings for Tiling Shell Extension !!
Would be nice, if tilings could be associates to workspace : right click on workspace > tiling > show tiling selection window and allow to select one.
Overview Mode (Super Key) :  When a tiling is associated to a Workspace show with transparency and allow to drag'n drop apps
from dash into workspace tiling zone show by transparent rectangles...
This would make Tiling Shell better integrated into gnome normal usage ...

Thanks for understanding my point of view ;-)

**Comment by domferr** [comment]
Hey! Thank you for your suggestion! With this extension my focus is on extending default behavior of GNOME Shell or implement loved features from other OSs. Your idea would be something new, so let's see what other people think about it!

**Comment by in4matix** [comment]
Oh boy, my nerves !! Stop messing with perfection !! ;-)

**Comment by thyttan** [comment]
I do see your point @in4matix, the elegance of neatly packed opinionated software can be nice!

However, I sympathise somewhat with @PHHENS here. But my take on it is this:

- A new workspace starts with a selected default layout (configurable) or inherits the layout of the previously active workspace.
- Workspaces layouts should be independent of each other. The selected layout of an unfocused workspace should not change if I change the layout when on another workspace.
- The Tiling Shell top bar icon should be dynamic and update to indicate what the active layout looks like.

I personally think that this would go a really long way!

**Comment by PHHENS** [comment]
Hi thyttan,
I agree with your detailled ideas, in addition : 
- Overview view (super key) : tiling zones should appear as transparent rectangles, so that apps can be drag and dropped from dash directly to the tiling zone
- Application view (super + clic on app grid in the dash) : show the different workspace with associated tiling zones (transparent rectangles), so that apps could be directly drag and dropped into the desired tiling zone (transparent rect) on the desired workspace.

This integrates tiling with gnome normal usage.
Thanks for supporting this idea.

**Comment by domferr** [comment]
Hey guys thank you for sharing you ideas: I love the brainstorming thing that is going on here :smile:. Unfortunately some of the suggestions cannot be done due to some GNOME limitations. 

I do know that there are people which prefer to have a different layout in different workspaces. It would be nice to understand why they prefer to do so and what is their daily workflow, so we can create a feature that can nicely keep the things simple but straight to the point! 

> - A new workspace starts with a selected default layout (configurable) or inherits the layout of the previously active workspace.
> - Workspaces layouts should be independent of each other. The selected layout of an unfocused workspace should not change if I change the layout when on another workspace.

I think this is very good. 
___
So, this is to summarize the support of per-workspace layout:
- The feature must be enabled from the settings
- The layout indicator will work and will look like as always, but the layouts shown are the ones in the active workspace
- The layout can be selected as it is done now: from the indicator menu. However, that would select the layout of the active workspace. The selected layout of an unfocused workspace won't change

**Comment by lasssim** [comment]
@domferr your summary makes total sense and would perfectly fit my workflow. 

I like to have one workspace for communication (email, slack, etc.) where i have more tiles and a different arrangement than on my productive workspaces where I have VSCode fill up most of the space with a narrow browser next to it.

**Comment by Willlum** [comment]
@domferr Just wanted to add my interest in a feature like this. Thanks for the great work!

**Comment by domferr** [comment]
Hey, quick update for you! I made an initial version and I'd like to share it with you! :star2:  Please test it for a while if you want, any feedback is much appreciated! I need your help to test this extensively so be aware that it may have bugs.

- For GNOME Shell versions 45, 46 and 47: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17541167/tilingshell%40ferrarodomenico.com.zip)
- For GNOME Shell versions from 42 to 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/17541165/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)

> To know your GNOME Shell version, run `gnome-shell --version`.
> 
> Extract the downloaded archive. Copy its content to `~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com` directory. You need to reload GNOME Shell afterwards (e.g. by logging out). Then you can enable the extension:
> ```
> /usr/bin/gnome-extensions enable tilingshell@ferrarodomenico.com
> ```

**Comment by Sorensiim** [comment]
Just tested it at the office and it works *perfectly*! 

https://github.com/user-attachments/assets/b0efae33-b80f-47d1-9a7b-5a447eb4726e

**Comment by domferr** [comment]
> Just tested it at the office and it works _perfectly_!
> Screencast.from.2024-10-29.08-24-18.mp4

Oh yeah, this is great! Thank you so much for your feedback

**Comment by domferr** [comment]
:star: Now available in Tiling Shell v14.1!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>

**Comment by lasssim** [comment]
@domferr thank you so much, this is awesome! :heart:
