### ISSUE TITLE
[Feature Request] A hotkey to expand the current tile

### ISSUE THREAD

**Issue by geeksville** [domferr/tilingshell#48]
**Describe the feature you'd like**

Use case: 

* I have two main tiles filling the right side of my screen (and two smaller less critical tiles on the left)
* The top tile is my web browser, the bottom is my code editor (vscode)
* It would be great if there was a hot key (Alt-Shift-Z or something) I could click.  If click it would verttically expand the tile under the cursor by 150% (temporarily shrinking other tiles in that column).  When the combo is clicked again it would reverse that change.
* This would allow me to make my web browser have a lot more screen realestate sometimes.  Or my code editor other times.
* Possibly if Ctrl is also pressed instead expand the tile in the horizontal direction.

**Additional context**
I love your extension!  Thanks!  I'm an active github coder but alas this is a bit outside of my wheelhouse, otherwise I'd give a PR a shot.

**Comment by domferr** [comment]
Hey! Thank you for your suggestion! With this extension my focus is on extending default behavior of GNOME Shell or implement loved features from other OSs. Your idea would be something new, so let's see what other people think about it!

**Comment by domferr** [comment]
Closing this. It will be tracked by #45
