### ISSUE TITLE
Because of zip format all the release files are 777 mode

### ISSUE THREAD

**Issue by EfogDev** [domferr/tilingshell#53]
**Describe the bug**
It may be better to use tar to preserve permissions. 

**To Reproduce**
1. Download a release
2. Unzip

**Screenshots**
![image](https://github.com/domferr/tilingshell/assets/7541981/4f0ba6bc-d9aa-4496-9827-0938f5130465)

**Information (please complete the following):**
 - Tiling Shell version: 10.0
 - GNOME version: 46.2

**Comment by domferr** [comment]
Hi, thank you for this suggestion! I agree with you, next releases will have `tar` files :sunglasses:
