### ISSUE TITLE
[Feature Request] Maximize a window by dragging it to top edge (top edge-tiling)

### ISSUE THREAD

**Issue by 7HE-W0R1D** [domferr/tilingshell#55]
**Describe the bug**
When dragging a window up to the top and release, the window is occupying the whole monitor, however, the window is not maximized to fit the monitor but resized to make its width and height equal to the space. Which makes the rounded corners persistent in the windows, and wasting some space for programs that uses a different layout in full screen (Firefox for example)

Program maximized to full screen:
![image](https://github.com/domferr/tilingshell/assets/42311695/53d50c90-defb-4c52-8656-48a2bf0da8a7)

Program dragged to full screen with tilingshell (notice the rounded corners and the shrank tab bar):
![image](https://github.com/domferr/tilingshell/assets/42311695/9644fecd-07dd-4579-aa7f-667eea6c902b)

**To Reproduce**
1. Go to tiling shell settings
2. Set `outer gaps` to `0`
3. drag any window to the top and release
4. the window would take up the whole space but its not in full screen.

**Information (please complete the following):**
 - Tiling Shell version: v10.0
 - GNOME version: 46.2

**Additional context**
I'm not sure if its the intended behavior / there are any setting on this that I missed, but I'm happy to test & provide more information if needed!

**Comment by EfogDev** [comment]
I double this; edge tiling from the v10.0 update changed this. For me the expected behavior on "drag to the very top and release" is to maximize a window, with no outer gaps (even if they are present in the settings).

**Comment by domferr** [comment]
Hey, thank you for this suggestion! 

In general, when you drag to the top, Tiling Shell doesn't maximize. I think, as you suggest, it makes sense to maximize the window if the outer-gaps are set to zero. However, I'm now changing my mind: maybe it is better to always maximize, even if you have set outer-gaps to some value. What do you think?

**Comment by EfogDev** [comment]
@domferr I believe this really makes more sense.
https://github.com/domferr/tilingshell/pull/56

**Comment by domferr** [comment]
> What about folks like me that never use maximized windows? It is part of my workflow now to grab a window to the top and dropping it into a tiling zone.

Yeah, me too ahahah can't live without Snap Assistant!
They are talking about edge-tiling: by moving the window on the top edge (above the snap assistant), the extension currently doesn't maximize the window, but sets the window to the maximum size instead. GNOME's default behavior is to maximize, while Tiling Shell overwrites that behavior.

[Screencast from 2024-06-27 10-58-54.webm](https://github.com/domferr/tilingshell/assets/14203981/5fb3e709-534c-451b-b174-5e395c5a7a82)

**Comment by in4matix** [comment]
@domferr , ooohh, dragging the window to the top EDGE maximizes it... Sorry, I'm stupid :-)

**Comment by cnhy0** [comment]
Is there an option to use the default full screen instead of the full screen with gaps? I would like to use tiling shell but still use default full screen

**Comment by domferr** [comment]
Hi @cnhy0, this is currently not possible, but it will be customizable in next updates

**Comment by domferr** [comment]
Meanwhile, as a workaround, you have many options:
- use the version before ([v9.1](https://github.com/domferr/tilingshell/releases/tag/9.1.0)), which doesn't include edge-tiling.
- keep version 10 and use the maximize button (but that is obvious).
- wait for the next major release, which will introduce a way to enable/disable/customize edge-tiling. If the work takes longer than expected, I will publish a minor release to let people enable or disable edge-tiling (and use the default one).

**Comment by domferr** [comment]
Hi, in the next update it will be possible to choose whether to maximize the window or not when it is dragged to the top edge :partying_face:. It will be possible to enable/disable edge-tiling too.

<p align="center">
<img src="https://github.com/domferr/tilingshell/assets/14203981/33abd642-cf13-4fc2-96b8-575fc1c1f63b" width=400 />
</p>

If you want to try it in advance, here it is!

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16039588/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16039589/tilingshell%40ferrarodomenico.com.zip)

Enjoy!
