### ISSUE TITLE
[Feature Request] "Enable Tiling System" by right mouse button

### ISSUE THREAD

**Issue by Humpix** [domferr/tilingshell#64]
Would it be possible to make the right mouse button selectable for the "Enable Tiling System" option?

The idea would be that "Enable Tiling System" is activated when you press and hold the right mouse button while moving a window with the left mouse button. In principle exactly the same as the already selectable hotkeys.

the right mouse button makes a lot of sense as a hotkey, since you're already holding the mouse in your hand anyway ;)
Just throwing this out there as an idea and thanks for the great work!!!

**Comment by domferr** [comment]
Hey, thank you for sharing your idea and support!
I'm not sure it can be done, unfortunately. I'll do some research :+1:

**Comment by percolator25** [comment]
I would also really appreciate this feature because you than can manage the windows only by mouse and have the other hand free to hold your coffee cup or for face palming.

**Comment by domferr** [comment]
@percolator25 thank you for your feedback.

After some research, unfortunately the only thing I can tell is that it cannot be done: GNOME aborts dragging if you do right click while dragging a window :disappointed:.

I'm keeping this open because I'm still looking around to understand if it is doable

**Comment by percolator25** [comment]
Thank you for checking and the fast response. Is this true for all mouse buttons? Maybe something like dragging with middle mouse button or one of the extra buttons does work (my mouse has 6)?

**Comment by domferr** [comment]
> Maybe something like dragging with middle mouse button or one of the extra buttons does work

@percolator25 :open_mouth: this is cool! I've a mouse with multiple buttons too, so I can test it. However, I'm not sure how to do it, I'll think about it. Thank you for the idea!

**Comment by domferr** [comment]
Quick update: unfortunately there is no way in GNOME to check whether the extra mouse buttons where pressed or not, I'm sorry :disappointed:
