### ISSUE TITLE
[Feature Request] Keep tiling layout on the overview

### ISSUE THREAD

**Issue by mattdm** [domferr/tilingshell#65]
**Describe the feature you'd like**

When I hit the super key (or use the top-left control or hot corner), I would like the "exploded" view to reflect the current tiling layout, so I can quickly find windows without confusion and cogitative overhead.

If there is just one window in a given tile, show that window in the exact same space. If there are multiple windows stacked in a tile, show them in the corresponding area, but spread out. (First thought was top-to-bottom corresponding to z order -- but, since that changes, it's probably better to keep them in the order in which they were added to that tile.)

**Additional context**

I've used the Native Window Placement extension for years. I've found it makes the location of windows in the exploded view more intuitive to me. (Your mileage may vary.) However, when used with Tiling Shell, _neither_ mode (NWP or not) really makes sense.

**Comment by domferr** [comment]
Thank you for sharing your idea! I think it makes sense. There is only one edge case that cannot be covered: if you have some non tiled windows, they need to be showed in the overview somewhere, breaking the "layout".

> so I can quickly find windows without confusion and cogitative overhead

This is important! I've got the same confusion, the user experience is not great there :\

**Comment by domferr** [comment]
Unfortunately, after some research, I came to the conclusion that it is not possible to keep the tiling layout in the overview.
