### ISSUE TITLE
Permission to package this for NixOS?

### ISSUE THREAD

**Issue by Neon-44** [domferr/tilingshell#68]
while you can install gnome extensions normally in NixOS, that's really not the point of it. The whole idea is that all your packages are nixpks that you add centrally to your configuration.nix

As such, I would like to package this extension as a nixpkg so I can add it to my config and install it declaratively.

But I know from the whole manjaro-debacle that this can actually lead to problems for the maintainers. As such I would like to first ask for your permission to package this extension :)

**Comment by domferr** [comment]
Hi! Thank you for opening this issue. As you can imagine, it would be better for everybody to avoid creating that package. Thank you for your understanding!

**Comment by hellconnon** [comment]
I wish the whole internet was like this ...
