### ISSUE TITLE
[Feature request] Switch focus between tiled windows with keybindings

### ISSUE THREAD

**Issue by thyttan** [domferr/tilingshell#69]
I would like to switch focus between the tiled windows with keybindings - similarly to how a focused window can be moved around in the current version of `Tiling Shell`.

- Personally I would want to bind this to `ALT`+`h/j/k/l`
- Maybe have an additional, fifth, keybinding to cycle through windows that are tiled in the same position (i.e. sits in front of/behind each other).
- Unsure on how maximized windows should interact with this feature.
  - Maybe maximized windows are considered to be positioned above the top-tiled windows?
  - Or maybe the maximized window is returned to its tiled size and position?
  - Or maybe the feature is disabled when the focused window is full screen?
- Unsure on how/if floating/non-tiled windows should interact with this feature.
  - Maybe the floating positions of floating windows in relation to the tiled ones are considered when using the keybindings to switch the focus between windows?
  - Maybe they are disregarded?

Standard `ALT`+`TAB`-ing in all its glory, but it can be a little clumbsy/imprecise/unpredictable to me.

As always thanks for Tiling Shell and for considering!

**Comment by domferr** [comment]
Hey, thank you for your suggestion! This would be something new, let's see what people think about it!

**Comment by domferr** [comment]
Hey, quick update for you. This is going to be released with next Tiling Shell update. However, to start with, you will be able to focus both tiled and non-tiled windows.

[Screencast from 2024-10-06 17-34-01.webm](https://github.com/user-attachments/assets/754003ea-3294-422a-9db1-79cdb990a061)

**Comment by thyttan** [comment]
Looks really neat!

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!
