### ISSUE TITLE
Snap window from window menu

### ISSUE THREAD

**Issue by domferr** [domferr/tilingshell#74]
Show the snap assistance when you right click on the window! This is coming soon with the next update:

[Screencast from 2024-07-06 19-51-18.webm](https://github.com/domferr/tilingshell/assets/14203981/b8c5ce0c-7e21-4518-a8b2-8bf5b602cd52)

**Additional context**
The original idea was to show the snap assistance when hovering the maximize button (as it is done on Windows 11). Unfortunately, GNOME doesn't let us handle the hovering of the maximize button or add another button near it.

**Comment by in4matix** [comment]
Looks amazing. Good enhancement.

**Comment by domferr** [comment]
> Looks amazing. Good enhancement.

Thank you for your feedback!

**Comment by domferr** [comment]
MacOS introduced something like this feature recently, but it uses strict layouts only. Here it is:
<p align="center">
<img src="https://github.com/domferr/tilingshell/assets/14203981/eecbe8d6-b61d-4ca1-8164-c66772d1dc2e" />
</p>

My opinion is that there are too many options. Moreover, GNOME's design has more padding and the whole menu takes a lot of space, so we cannot afford adding so many options.

**Comment by domferr** [comment]
A quick update :partying_face: 

![image](https://github.com/domferr/tilingshell/assets/14203981/2f8d845e-32c3-4c51-a3f7-24cbbae30613)

**Comment by in4matix** [comment]
Wow looks amazing !

**Comment by cheddarnaz** [comment]
Hey, didn't have any other issue to comment this on @domferr but I thought this may be a good issue to let you know that this extension has been such a life saver for me, and the work that's been put into the multi monitor layout support recently has really enabled GNOME to have the exact workflow I need. Thank you. You're amazing.

**Comment by domferr** [comment]
Hey @cheddarnaz thank you for the kind words :heart: I'm so happy you are enjoying Tiling Shell!

**Comment by domferr** [comment]
:star: This feature is now available!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
