### ISSUE TITLE
Auto-resize of complementing windows does not work when resizing with window-action key

### ISSUE THREAD

**Issue by christopher-l** [domferr/tilingshell#76]
**Describe the bug**
GNOME has a feature to resize a window by holding the window-action key (<kbd>Super</kbd> by default) and a mouse button (middle-click by default). This way, the resize action can be started anywhere within the window without moving the cursor to the window border. When using this method, the "auto-resize complementing tiled windows" option does not work.

**To Reproduce**
1. Place two windows next to each other using Tiling Shell
2. Place the cursor near the border between the two windows but still above one of the windows
3. Hold <kbd>Super</kbd> and the middle mouse button
4. Move the cursor

![image](https://github.com/domferr/tilingshell/assets/1208506/ee189055-1f7a-46e5-9b85-7ca05812d683)

**Information**
 - Tiling Shell version: v10.0
 - GNOME version: 46

**Comment by domferr** [comment]
Hey @christopher-l thank you for opening this issue!

:open_mouth: :open_mouth: I didn't know about this feature of GNOME! Thanks a million for writing the steps to reproduce the problem. I'm going to work on this

**Comment by domferr** [comment]
:star: This was fixed by the latest update of Tiling Shell!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
