### ISSUE TITLE
Add buttons for automatic window tiling to window menu

### ISSUE THREAD

**Issue by in4matix** [domferr/tilingshell#77]
I would like to look at a window, wink at it, then look at a point on the desktop, then wink again and then the window must go tile itself there.

I'm lazy... Sorry...

**Comment by domferr** [comment]
Ahahahahahah, I love it!

Is right clicking on the window considered as valid as winking? :)
It may be cool to have a button labeled "Auto-tile" in the menu that shows up when you right click on a window. If you press it, the window will be tiled to nearest tile (or to an empty tile, or to a tile that has similar size, or [put here any idea you may have]).

Uh, maybe multiple buttons!
- Tile to the nearest tile
- Tile to an empty tile
- Tile to a similar tile

**Comment by in4matix** [comment]
> It may be cool to have a button labeled "Auto-tile" in the menu that shows up when you right click on a window. If you press it, the window will be tiled to nearest tile

Lol, sorry about the satire. I'm quite happy with the original functionally ;-) But I am sure many other users would love it.

**Comment by domferr** [comment]
Yeah don't be sorry, the whole joke was very useful for me because it gave me that idea ahahaha [^1]
We will see this feature coming in the next release :partying_face: 

[^1]: Finally, something new **NOT** related to keyboard... :smile:

**Comment by in4matix** [comment]
What would be cool is a button or hotkey to automagically tile all open windows whether they are minimized or cascaded. Afterwards, one can just resize them as wanted.

**Comment by domferr** [comment]
My goal (to be done in the future, maybe later than september) is to have a button or hotkey to automagically tile the open windows based on your previous activities. So, for example:
- if you are used to tile firefox in the middle, it will be placed there
- if you are used to tile firefox in the middle with the terminal on the left and you have both firefox and the terminal open, they will be placed like you are used to

Of course this is just an idea: it is not clear yet how much effort is needed to implement all of this in a reliable way. For sure, it will be fun :)

**Comment by in4matix** [comment]
Another possibility is a list in settings to set where certain windows should tile. Also, not sure if already possible as I have not opened settings since version 5, is to re-arrange already tiled windows by dragging them around and then they just swap positions.

**Comment by domferr** [comment]
:star: This is now available!
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>

**Comment by in4matix** [comment]
Hey,
Any reason why I cannot update from GSE ? (I never did the version mod)

![Screenshot from 2024-07-22 08-00-25](https://github.com/user-attachments/assets/11a5745c-8cad-47a5-90da-875983ec73e1)

**Comment by domferr** [comment]
Hey, you are using a GNOME shell version below 45, right? They still have to accept Tiling Shell's update for GNOME 42-44. Maybe that's the reason

**Comment by in4matix** [comment]
Hi, Yes I'm using Ubuntu 22.04, Gnome 42.9. Okay, that is the reason then. Thanks !
