### ISSUE TITLE
[Feature Request] Snap Assistant not showing on touch devices

### ISSUE THREAD

**Issue by palexdev** [domferr/tilingshell#82]
**Describe the bug**
The Snap Assistant popup does not show (not properly at least) when using touchscreens

**To Reproduce**
1) You need a touchscreen
2) Drag a window
3) Observe that the Snap Assistant popup is not shown properly

**Screenshots**
https://github.com/domferr/tilingshell/assets/16880178/b0553d1e-e4e3-458a-aee8-6e1dd43650db

**Information (please complete the following):**
 - Tiling Shell version: v11.0
 - GNOME version: 46.3.1

**Additional context**
The device I'm experiencing the issue on is an Android tablet that I modded to use Linux. I have a bluetooth keyboard, and as you can see in the video (when the cursor appears I'm using the keyboard's trackpad) it works properly with it.
Let me know if you need logs or anything else and how to collect them

**Comment by domferr** [comment]
Hey @palexdev thank you for sharing this! I didn't test Tiling Shell on touch devices, but thanks to you we can assume that it does not work ahaha. I'm looking to add this feature! Hope to give you an update soon :partying_face:

**Comment by palexdev** [comment]
Thank you very much @domferr your awesome extension is the last piece to complete my setup, looking forward to it 😄

**Comment by domferr** [comment]
Hey @palexdev I'm writing to give you a quick update. I hoped to implement this in few days and after some research it turned out that GNOME doesn't provide to extensions a way to know the touch position _while_ moving the window. I'm looking into ask them :wink: and I'll tell you whether this is doable or not!

**Comment by palexdev** [comment]
Ah yes I see the problem now

It's a bit sad considering that GNOME is one of the best environments when it comes to touch support 

The workaround could work in theory. I don't know the behavior at the edges, but I _think_ the major issue is going to be precision. Still better than nothing though

**Comment by domferr** [comment]
Hey @palexdev I've got very good news for you :smile: 

I implemented my workaround and it seems to work on my touch device! Please consider it is a rough version, test it for a while if you can and let me know of any bug or missing features!

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16176618/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16176620/tilingshell%40ferrarodomenico.com.zip)

___

If you don't know how to install, here it is a little guide for you. You need to perform the following steps: overwrite the files into `.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com` with the ones in the archive I shared, then log out and log in (or restart the system).

**Comment by domferr** [comment]
Another update, with bugs fixed. It seems to work, but some everyday testing is still needed. I'll leave here the updated version, with touch support!

- GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16180106/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16180107/tilingshell%40ferrarodomenico.com.zip)

**Comment by domferr** [comment]
Touch support is now available on Tiling Shell! :star:
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>

**Comment by palexdev** [comment]
@domferr hello, sorry for not reporting back sooner, it's been a very busy week
The new version indeed fixes the snap assistant, but it's still buggy on my device
Here's a video: https://github.com/user-attachments/assets/99b62405-5e55-414d-9a41-f70bf53954f1

As you can see, two issues:
1) Precision at edges is not great (I can live with that tbh)
2) The snap assistant does not place windows as intended, this is a major issue

**Comment by domferr** [comment]
Hey thank you for the video. I'm curious: does it happen with apps that need on-screen keyboard only?

Can you confirm that the highlighted tile of the snap assistant is the right one (the one under your finger)?

**Comment by domferr** [comment]
A quick update: it seems a bug of the latest version (#99).

I'm publishing a bugfix for that which will solve yours as well
