### ISSUE TITLE
[Feature Request] Add a key-binding to untile a window.

### ISSUE THREAD

**Issue by qukhan** [domferr/tilingshell#83]
**Describe the feature you'd like**
We have key bindings to tile windows but we don't have one to do the reverse operation. It would be nice to avoid having to reach out to get the mouse just to untile a window.

**Comment by domferr** [comment]
Hey @qukhan thank you for sharing this idea! I think it makes sense, which default keybinding you think would be a good one?

**Comment by qukhan** [comment]
I'm not sure. I don't know if it's intended but my current setup has <kbd>Meta</kbd> + <kbd>↑</kbd> maximize the window when it can't go up anymore. So I'd say having <kbd>Meta</kbd> + <kbd>↓</kbd> untile the window when it can't go down anymore would feel the most intuitive.

**Comment by thyttan** [comment]
I vote against tying it to `super`+`down`. I'd prefer a separate keybinding.

But also, I think there's already a solution to this without tweaking `Tiling shell`.

There's a keyboard shortcut in the GNOME settings called 'Toggle fullscreen mode' that's disabled by default. You could set that to e.g. `meta`+`ctrl`+`up` to toggle between full screen and floating position.

There's also a 'Toggle maximization State' one.

https://help.gnome.org/users/gnome-help/stable/keyboard-shortcuts-set.html.en (under the section 'Windows')

**Comment by domferr** [comment]
Yeah @thyttan, <kbd>SUPER</kbd> + <kbd>↓</kbd> is already used for so many things. @qukhan idea may work, however if you press <kbd>SUPER</kbd> + <kbd>↓</kbd>, and the window cannot be tiled on its monitor and you have a monitor below, Tiling Shell will move the window to the other monitor

I'm curious about the needs of this feature: if one wants to untile with keyboard because he/she doesn't want to use the mouse to do it, then after the window is untiled I believe that person would use the mouse to move the window... :smile:  

I believe that defining the ideal use case and reasons behind this feature would automatically tell us the right keybindings :wink:

**Comment by qukhan** [comment]
If the debate is about what key to set by default, I don't have a preference.

I generally don't work in maximized windows (for plenty of possible reasons: the app layout isn't convenient for large screens, I want to see some other app interface in the background, I want the app to be in a specific part of the screen, etc). When I need to put two windows side by side, I tile them, do what I have to do, then close the one that isn't used anymore and un-tile the first one so that it moves back to its original position.

> if you press <kbd>SUPER</kbd> + <kbd>↓</kbd>, and the window cannot be tiled on its monitor and you have a monitor below, Tiling Shell will move the window to the other monitor

Didn't this already work with the default Gnome shortcut <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>↓</kbd>? I've been using that and it works well. The behaviour you described however doesn't seem to work (I'm guessing it will in the next version).

**Comment by distefam** [comment]
I would suggest `Super` + `f`, which is frequently used by tiling window managers and has the mnemonic to "float" a window (i.e., not tile it). Another option would be `Super` + `t` for "tile". "Float" seems to indicate that the default behavior is to tile, while "Tile" would be more useful if the default behavior is to "float" a window.

**Comment by domferr** [comment]
Hey guys, here we go! This is going to be released with the next update of Tiling Shell. If you want to try it in advance and give some feedback, I leave here the files. Enjoy!

- GNOME shell version 42, 43 or 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16550098/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME shell version 45 or 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16550099/tilingshell%40ferrarodomenico.com.zip)

**Comment by domferr** [comment]
:star: Now available in [Tiling Shell v13](https://github.com/domferr/tilingshell/releases/tag/13.0.0)!
