### ISSUE TITLE
Right Click on touchpad doesn't work

### ISSUE THREAD

**Issue by Vadmacska** [domferr/tilingshell#91]
**Describe the bug**
On an HP Spectre laptop, the right-click touchpad button does not work when creating a new layout. The dividing line cannot be removed.

**To Reproduce**
1. Go to  Create new Layout 

**Information (please complete the following):**
 - Ubuntu 22.04.4 LTS
 - GNOME Shell 42.9

**Comment by domferr** [comment]
Hey, thank you for opening this issue. Does the left-click on touchpad work?

**Comment by Vadmacska** [comment]
Yes, it works correctly Right click on the corner and double finger touch.

**Comment by Vadmacska** [comment]
Everything seems okey I updated plugin. Sorry for bothering. :)
