### ISSUE TITLE
12.0 preview: tiling with keyboard is broken

### ISSUE THREAD

**Issue by EfogDev** [domferr/tilingshell#94]
**Describe the bug**
After updating from v11 to v12, tiling with the keyboard is unusable. Something is happening in very wrong and unpredictable way.

**To Reproduce**
1. Have multiple monitors I believe
2. Have different layouts
4. Open a window and try to tile it with the keyboard

**Screenshots**
See the video: https://github.com/user-attachments/assets/150a8ba1-2ed4-4040-ae8d-d04435536861

**Information (please complete the following):**
 - Tiling Shell version: 12.0
 - GNOME version: 46.3.1

**Additional context**
![image](https://github.com/user-attachments/assets/0c1904b9-8da5-433c-adfb-332a6d402f05)
![image](https://github.com/user-attachments/assets/f96db059-f11c-47f3-ae02-e3d5f5415e6f)

**Comment by domferr** [comment]
Hey @EfogDev thank you for sharing this bug (and for the amazing video too! :smile: )

I'm looking into this, the version 12 introduces the ability to move the window across monitors using keybindings. It seems that it doesn't always work lol...

**Comment by domferr** [comment]
@EfogDev I updated the release files, check that out! It has the bugfix to your problem

**Comment by EfogDev** [comment]
@domferr just tried — works nice so far! Thanks!
