### ISSUE TITLE
[Feature Request] Customize snap assistant threshold trigger

### ISSUE THREAD

**Issue by andyalv** [domferr/tilingshell#95]
I started using this extension on a small laptop and think it would be great to customize the snap assistant. Because of the reduced screen size, the snap assistant takes up a lot of space at the top of the screen, which makes slightly moving windows trigger the assistant. It would be nice to be able to reduce the assistant scaling and threshold trigger.

**Comment by domferr** [comment]
Hey, thank you for sharing your suggestion!

Are you referring to something like the behavior of this video ? Here the window triggers the snap assistant just because it is grabbed near it and not because the user wants to open the snap assistant.

[Screencast from 2024-07-17 19-46-08.webm](https://github.com/user-attachments/assets/e31ffa40-648f-4746-8705-d0f0f22fc5d3)

I'm curious to know how Windows 11 handles that!

**Comment by andyalv** [comment]
Yes, that's the thing I'm talking about. My screen is a bit bigger than 1280 x 720 and the snap assistant has a threshold of around 20% of the top of my screen. It also doesn't help that I experimented with new layouts, making the width of the overall assistant bigger when triggered.

I don't know what you mean with Windows 11, but I can think of a few things that may help. Modifying the trigger area to be smaller would be great, personally, I would like to have a smaller and more precise area, but that is a personal preference. I also believe that the assistant takes a lot of space when showing more layouts, I would expect it to be more "responsive" (hide the assistant when the cursor has been on it for a while but not a single layout has been selected or to have a faster response when the focus is lost).

**Comment by schijo** [comment]
+1. I'd like to second this feature request. Having a big screen but still the trigger area is a too big for my taste and behavior. Would be nice to be able to customize trigger area (in percent or pixel).

**Comment by domferr** [comment]
A quick update for you: this is going to be released next week!

**Comment by schijo** [comment]
Excellent. Thank you very much - for the feature and the swift delivery. :1st_place_medal:

**Comment by domferr** [comment]
:heavy_check_mark: Done in version 12.1! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
