### ISSUE TITLE
Auto Suggestions

### ISSUE THREAD

**Issue by ZombieArcade** [domferr/tilingshell#96]
I would like to see suggestions after snapping windows just like on Windows 11. For example, if I have running file manager and spotify, if I snap the file manager, it will automatically give me the option to snap Spotify in the remaining space. This feature exists in the Tiling Assistant extension, but not in this one

**Comment by domferr** [comment]
Hey, thank you for sharing your idea! I agree with you and I already planned that, I'm tracking this with the issue #62, hope to implement this soon :soon:. See you there!
