### ISSUE TITLE
The positioning is wrong for a few apps.

### ISSUE THREAD

**Issue by dhra** [domferr/tilingshell#99]
**Describe the bug**
When the user selects the left position, the app moves to the center instead of the left

**To Reproduce**
1. Enable Tilling Shell
2. Drag `gnome-terminal` on a custom layout section

**Screenshots**

https://github.com/user-attachments/assets/81909a3d-39b8-453d-8f16-7e15c668c0a1

**Information (please complete the following):**
 - Tiling Shell version: v12
 - GNOME version: 46.3.1

**Additional context**
No such issue exists on Firefox, Chrome, or Nautilus.
The issue exists on `GNOME Terminal 3.52.2`, `Gnome Text Editor 46.3`, and `Spotify 1.2.40`.

**Comment by domferr** [comment]
Hey @dhra thank you for sharing this bug! It does not happen to me with Spotify and GNOME Terminal, but I can confirm that I can reproduce this bug with GNOME Text Editor. I've got a fix already and I'm publishing it on GSE.

As soon as they accept the bugfix I'll write a comment here. When the bugfix gets published you should receive it almost immediately.

**Comment by domferr** [comment]
Update: the bugfix was accepted right now and you should be able to update Tiling Shell :star:
